<?php
function hidden($k,$v):void{echo '<input type="hidden" name="'.e($k).'" value="'.e($v).'">';}
function check($key,$title,$value=true,$attrs=''):void{echo '<label class="switch-row"><input type="checkbox" name="'.e($key).'" '.($value?'checked':'').' '.$attrs.'> '.e($title).'</label>';}
function deleteButton($action,$id,$text='حذف'):void{formstart($action);hidden('id',$id);echo '<button class="button secondary small" data-confirm="آیا از این عملیات مطمئن هستید؟">'.e($text).'</button></form>';}
function options($table,$where='1=1'):array{return ['0'=>'انتخاب نشده']+array_column(q("SELECT id,name FROM $table WHERE $where ORDER BY name")->fetchAll(),'name','id');}
function adminStaff():void{need('staff');$id=(int)($_GET['id']??0);$u=$id?q('SELECT * FROM staff WHERE id=? AND deleted=0',[$id])->fetch():null;layout('staff','همکاران و دسترسی‌ها','حساب مستقل، محدوده اطلاعات و مجوز هر عملیات را تعیین کنید.');echo '<section class="panel form-panel"><div class="staff-cards">';foreach(q('SELECT id,name,username,role,active FROM staff WHERE deleted=0 ORDER BY id')->fetchAll() as $r){echo '<a class="staff-card" href="/staff?id='.$r['id'].'#edit"><span class="mini-avatar">'.e(mb_substr($r['name'],0,1)).'</span><strong>'.e($r['name']).'</strong><small>'.e($r['username']).' · '.($r['active']?'فعال':'غیرفعال').'</small></a>';}echo '</div><a class="text-link" href="/staff">افزودن همکار جدید +</a></section>';
 $importedPractitioners=q("SELECT sp.source_name,m.staff_id,s.name,s.username,s.active,COUNT(e.id) visit_count
   FROM import_source_practitioner_map m
   JOIN import_source_practitioners sp ON sp.id=m.source_practitioner_id
   JOIN staff s ON s.id=m.staff_id
   LEFT JOIN import_patient_events e ON e.therapist_id=s.id
   GROUP BY sp.id,sp.source_name,m.staff_id,s.name,s.username,s.active
   ORDER BY visit_count DESC,sp.source_name")->fetchAll();
 if($importedPractitioners){echo '<section class="panel form-panel"><div class="panel-header"><h2>درمانگرهای واردشده از بقراط</h2><span class="count">'.fa(count($importedPractitioners)).'</span></div><p class="hint">این حساب‌ها هنگام انتقال به‌صورت غیرفعال ساخته شده‌اند و تا زمانی که مدیر آن‌ها را فعال و برایشان رمز تعیین نکند امکان ورود ندارند.</p><div class="table-scroll"><table><thead><tr><th>نام در بقراط</th><th>پروفایل مسیحا</th><th>ویزیت تاریخی</th><th>وضعیت ورود</th><th></th></tr></thead><tbody>';foreach($importedPractitioners as $r)echo '<tr><td>'.e($r['source_name']).'</td><td>'.e($r['name']).'<small>'.e($r['username']).'</small></td><td>'.fa($r['visit_count']).'</td><td>'.($r['active']?'فعال':'غیرفعال').'</td><td><a href="/staff?id='.(int)$r['staff_id'].'#edit">مدیریت</a></td></tr>';echo '</tbody></table></div></section>';}
 if(allowed($id?'staff.edit':'staff.create')&&(!$u||$u['role']!=='admin'||user()['role']==='admin')){echo '<section class="panel form-panel" id="edit">';sectiontitle($id?'ویرایش همکار':'ساخت همکار');formstart('staff');hidden('id',$id);echo '<div class="form-grid">';field('name','نام و نام خانوادگی',$u['name']??'','text','نام نمایشی در نوبت‌ها و گزارش‌ها.',true);field('username','نام کاربری',$u['username']??'','text','حداقل سه حرف انگلیسی یا عدد.',true);field('password','رمز ورود جدید','','password','حداقل ۱۲ نویسه. برای حفظ رمز فعلی خالی بگذارید.',!$id);$roles=['reception'=>'پذیرش','therapist'=>'درمانگر','finance'=>'امور مالی'];if(user()['role']==='admin')$roles=['admin'=>'مدیر کلینیک']+$roles;selectfield('role','نقش پایه',$roles,$u['role']??'reception','مدیر به همه بخش‌ها دسترسی دارد؛ سایر نقش‌ها از تنظیمات جزئی پیروی می‌کنند.',true);echo '</div>';check('active','حساب فعال',$u['active']??true);formend('ذخیره همکار','/staff');if($id&&allowed('staff.delete')&&$u['role']!=='admin')deleteButton('staff_delete',$id,'حذف حساب');echo '</section>';}
 if($u&&$u['role']!=='admin'&&user()['role']==='admin'){$p=permissions($u);echo '<section class="panel form-panel">';sectiontitle('دسترسی‌های '. $u['name'],'تغییرات پس از ذخیره فوراً در همه درخواست‌ها اعمال می‌شوند.');formstart('permissions');hidden('id',$id);echo '<div class="form-grid">';foreach(['profile'=>'مشاهده پروفایل مراجع','contact'=>'مشاهده اطلاعات تماس','forms.visit'=>'فرم‌های ویزیت و درمان','forms.general'=>'فرم‌های عمومی'] as $k=>$v)selectfield('scope['.str_replace('.','_',$k).']',$v,str_starts_with($k,'forms.')?['none'=>'هیچ فرم','own'=>'فقط فرم‌های ثبت‌شده توسط خود کاربر','all'=>'همه فرم‌های مراجع مجاز']:['none'=>'هیچ‌کس','related'=>'فقط مراجع مرتبط','all'=>'همه مراجعین'],$p[$k],'مراجع مرتبط: ثبت‌کننده پرونده، مسئول پرونده یا درمانگر دارای جلسه.');echo '</div>';foreach(permissionGroups() as $group=>$items){echo '<fieldset class="permission-group"><legend>'.e($group).'</legend><div class="actions"><button type="button" class="button secondary small" data-check-group="1">انتخاب همه</button><button type="button" class="button secondary small" data-check-group="0">عدم دسترسی به همه</button></div><div class="permission-grid">';foreach($items as $k=>$title)check('perm['.str_replace('.','_',$k).']',$title,$p[$k]);echo '</div></fieldset>';}formend('ذخیره دسترسی‌ها','/staff');echo '</section>';}endLayout();}
function labelsView():void{need('labels');$id=(int)($_GET['id']??0);$r=$id?q('SELECT * FROM labels WHERE id=? AND deleted=0',[$id])->fetch():null;layout('labels','لیبل‌های مراجعین','برچسب رنگی برای تشخیص سریع نوع مراجعه؛ لیبل پیش‌فرض هنگام نوبت‌دهی اعمال می‌شود.');echo '<section class="panel form-panel"><div class="staff-cards">';foreach(q('SELECT * FROM labels WHERE deleted=0')->fetchAll() as $v){echo '<div class="staff-card"><span class="badge" style="color:'.e($v['color']).'">'.e($v['name']).'</span><small>'.($v['is_default']?'پیش‌فرض · ':'').($v['active']?'فعال':'غیرفعال').'</small>';if(allowed('labels.edit'))echo '<a href="?id='.$v['id'].'">ویرایش</a>';if(allowed('labels.delete'))deleteButton('label_delete',$v['id']);echo '</div>';}echo '</div></section>';if(allowed($id?'labels.edit':'labels.create')){echo '<section class="panel form-panel">';formstart('label_save');hidden('id',$id);echo '<div class="form-grid">';field('name','عنوان لیبل',$r['name']??'','text','مانند مراجعه اول یا دوره توان‌بخشی.',true);field('color','رنگ',$r['color']??'#087f75','color','رنگ نمایش لیبل.',true);echo '</div>';check('active','فعال',$r['active']??true);check('is_default','لیبل پیش‌فرض سامانه',$r['is_default']??false);formend('ذخیره لیبل','/labels');echo '</section>';}endLayout();}
function inventoryView():void{
 need('inventory');$id=(int)($_GET['id']??0);$item=$id?q('SELECT * FROM inventory_items WHERE id=?',[$id])->fetch():null;
 layout('inventory','انبار و کالا','کالاهای جاری مسیحا و سابقه مصرف منتقل‌شده از بقراط.');
 $items=q("SELECT i.*,
   CASE WHEN i.opening_quantity IS NULL THEN NULL ELSE i.opening_quantity+COALESCE(SUM(CASE WHEN m.affects_stock=1 THEN m.quantity_delta ELSE 0 END),0) END current_stock,
   -COALESCE(SUM(CASE WHEN m.movement_type='historical_usage' THEN m.quantity_delta ELSE 0 END),0) historical_usage
   FROM inventory_items i LEFT JOIN inventory_movements m ON m.item_id=i.id
   GROUP BY i.id ORDER BY i.active DESC,i.name")->fetchAll();
 echo '<section class="panel"><div class="panel-header"><h2>کالاها</h2><span class="count">'.fa(count($items)).'</span></div><div class="table-scroll"><table><thead><tr><th>کالا</th><th>واحد</th><th>قیمت فروش</th><th>موجودی جاری</th><th>مصرف تاریخی بقراط</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>';
 foreach($items as $v){echo '<tr><td>'.e($v['name']).'</td><td>'.e($v['unit']).'</td><td>'.money($v['sale_price_toman']).'</td><td>'.($v['current_stock']===null?'تعیین نشده':fa(rtrim(rtrim(number_format((float)$v['current_stock'],3,'.',''),'0'),'.'))).'</td><td>'.fa(rtrim(rtrim(number_format((float)$v['historical_usage'],3,'.',''),'0'),'.')).'</td><td>'.($v['active']?'فعال':'غیرفعال').'</td><td><a href="/inventory?id='.$v['id'].'">مدیریت</a></td></tr>';}
 echo '</tbody></table></div></section>';
 echo '<section class="panel form-panel">';sectiontitle($item?'ویرایش کالا':'کالای جدید');formstart('inventory_item_save');hidden('id',$id);echo '<div class="form-grid">';field('name','نام کالا',$item['name']??'','text','نام کالا در انبار و گزارش.',true);field('unit','واحد',$item['unit']??'عدد','text','مانند عدد، بسته، جفت.',true);field('sale_price_toman','قیمت فروش (تومان)',$item['sale_price_toman']??0,'number','قیمت جاری کالا.',true,false,'min="0"');echo '</div>';check('active','کالا فعال',$item['active']??true);formend('ذخیره کالا','/inventory');echo '</section>';
 if($item){echo '<div class="dashboard-grid"><section class="panel form-panel">';sectiontitle('موجودی شروع','مصرف تاریخی بقراط روی موجودی جاری اثر نمی‌گذارد. موجودی واقعی را از اینجا تعیین کنید.');formstart('inventory_opening');hidden('item_id',$id);field('opening_quantity','موجودی شروع',$item['opening_quantity']??'','number','موجودی واقعی در تاریخ شروع.',true,false,'min="0" step="0.001"');field('opening_as_of','تاریخ موجودی',($item['opening_as_of']??date('Y-m-d')),'date','تاریخی که موجودی شمارش شده است.',true);formend('ثبت موجودی شروع','/inventory?id='.$id);echo '</section><section class="panel form-panel">';sectiontitle('تعدیل موجودی','برای ورود، خروج، اصلاح شمارش یا کسری/اضافه موجودی.');formstart('inventory_adjust');hidden('item_id',$id);field('quantity_delta','تغییر موجودی','','number','مثبت: افزایش؛ منفی: کاهش.',true,false,'step="0.001"');field('occurred_on','تاریخ',date('Y-m-d'),'date','تاریخ اعمال تغییر.',true);field('note','شرح','','text','علت تعدیل.',true);formend('ثبت تعدیل','/inventory?id='.$id);echo '</section></div>';
 $moves=q("SELECT m.*,p.fname,p.lname FROM inventory_movements m LEFT JOIN patients p ON p.pid=m.pid WHERE m.item_id=? ORDER BY COALESCE(m.occurred_on,DATE(m.created_at)) DESC,m.id DESC LIMIT 100",[$id])->fetchAll();
 echo '<section class="panel form-panel"><h2>گردش کالا</h2><div class="table-scroll"><table><thead><tr><th>تاریخ</th><th>نوع</th><th>تعداد</th><th>مبلغ</th><th>بیمار</th><th>کد نوبت</th><th>اثر بر موجودی</th><th>شرح</th></tr></thead><tbody>';
 $labels=['historical_usage'=>'مصرف تاریخی بقراط','adjustment'=>'تعدیل','purchase'=>'ورود','sale'=>'فروش','return'=>'برگشت'];
 foreach($moves as $m)echo '<tr><td>'.jd($m['occurred_on']?:substr($m['created_at'],0,10)).'</td><td>'.e($labels[$m['movement_type']]??$m['movement_type']).'</td><td>'.fa(rtrim(rtrim(number_format((float)$m['quantity_delta'],3,'.',''),'0'),'.')).'</td><td>'.($m['total_toman']===null?'—':money($m['total_toman'])).'</td><td>'.($m['pid']?e(patientName($m)):'—').'</td><td>'.fa($m['appointment_code']?:'—').'</td><td>'.($m['affects_stock']?'بله':'خیر').'</td><td>'.e($m['note']).'</td></tr>';
 echo '</tbody></table></div></section>';}
 endLayout();
}
function servicesView():void{need('services');$tab=$_GET['tab']??'services';$id=(int)($_GET['id']??0);layout('services','خدمات و پکیج‌ها','تعرفه، دسته‌بندی، خدمات همکاران و سهم درمانگر.');echo '<nav class="tab-nav">';foreach(['services'=>'خدمات','tariffs'=>'تعرفه‌ها','source'=>'کاتالوگ بقراط','categories'=>'دسته‌بندی‌ها','packages'=>'پکیج‌ها','shares'=>'خدمات و سهم همکار'] as $k=>$title)echo '<a class="'.($tab===$k?'selected':'').'" href="?tab='.$k.'">'.$title.'</a>';echo '</nav>';
 if($tab==='tariffs'){
  $tariffId=(int)($_GET['tariff_id']??0);$tariff=$tariffId?q('SELECT * FROM service_tariffs WHERE id=? AND deleted=0',[$tariffId])->fetch():null;
  $rows=q("SELECT t.*,s.name service_name FROM service_tariffs t JOIN services s ON s.id=t.service_id WHERE t.deleted=0 AND s.deleted=0 ORDER BY t.active DESC,t.effective_from DESC,t.id DESC")->fetchAll();
  echo '<section class="panel"><div class="panel-header"><h2>تعرفه‌های خدمات</h2><span class="count">'.fa(count($rows)).'</span></div><div class="table-scroll"><table><thead><tr><th>خدمت</th><th>نوع</th><th>عنوان</th><th>قرارداد</th><th>مبلغ</th><th>بازه اجرا</th><th>وضعیت</th><th></th></tr></thead><tbody>';
  foreach($rows as $v){$type=$v['tariff_type']==='contract'?'قراردادی':'عادی';echo '<tr><td>'.e($v['service_name']).'</td><td>'.$type.'</td><td>'.e($v['title']).'</td><td>'.e($v['contract_name']?:'—').'</td><td>'.money($v['price_toman']).'</td><td>'.jd($v['effective_from']).' تا '.($v['effective_to']?jd($v['effective_to']):'بدون پایان').'</td><td>'.($v['active']?'فعال':'غیرفعال').'<small>'.e($v['source_system']==='boghrat'?'پایه انتقال از بقراط':'مسیحا').'</small></td><td><a href="?tab=tariffs&tariff_id='.(int)$v['id'].'#tariff-edit">ویرایش</a></td></tr>';}
  echo '</tbody></table></div></section><section class="panel form-panel" id="tariff-edit">';sectiontitle($tariff?'ویرایش تعرفه':'تعرفه جدید','تعرفه عادی، قیمت پیش‌فرض خدمت است؛ تعرفه قراردادی هنگام نوبت قابل انتخاب است.');formstart('tariff_save');hidden('tariff_id',$tariffId);echo '<div class="form-grid">';selectfield('service_id','خدمت',options('services','deleted=0'),$tariff['service_id']??0,'خدمت مرتبط با تعرفه.',true);selectfield('tariff_type','نوع تعرفه',['normal'=>'عادی','contract'=>'قراردادی'],$tariff['tariff_type']??'normal','تعرفه قراردادی نام قرارداد هم نیاز دارد.',true);field('title','عنوان تعرفه',$tariff['title']??'تعرفه عادی','text','مثلاً تعرفه عادی یا تعرفه قرارداد شرکت.',true);field('contract_name','نام قرارداد / سازمان',$tariff['contract_name']??'','text','برای تعرفه عادی خالی بگذارید.');field('price_toman','مبلغ (تومان)',$tariff['price_toman']??0,'number','مبلغ این تعرفه.',true,false,'min="0"');field('effective_from','شروع اجرا',$tariff['effective_from']??date('Y-m-d'),'date','تاریخ شروع اعتبار تعرفه.',true);field('effective_to','پایان اجرا',$tariff['effective_to']??'','date','اختیاری؛ خالی یعنی بدون پایان.');echo '</div>';check('active','تعرفه فعال',$tariff['active']??true);formend('ذخیره تعرفه','/services?tab=tariffs');if($tariffId)deleteButton('tariff_delete',$tariffId,'بایگانی تعرفه');echo '</section>';
 }
 elseif($tab==='source'){
  $srcServices=q("SELECT c.source_name,COUNT(x.id) uses_count,MIN(x.amount_toman) min_price,MAX(x.amount_toman) max_price,s.id service_id,s.name mapped_name,s.price mapped_price,m.mapping_mode FROM import_source_services c LEFT JOIN import_event_services x ON x.source_service_id=c.id LEFT JOIN import_source_service_map m ON m.source_service_id=c.id LEFT JOIN services s ON s.id=m.service_id GROUP BY c.id,c.source_name,s.id,s.name,s.price,m.mapping_mode ORDER BY uses_count DESC,c.source_name")->fetchAll();
  $srcGoods=q("SELECT c.source_name,COUNT(x.id) uses_count,COALESCE(SUM(x.quantity),0) quantity_total,MIN(x.amount_toman) min_price,MAX(x.amount_toman) max_price FROM import_source_goods c LEFT JOIN import_event_goods x ON x.source_goods_id=c.id GROUP BY c.id,c.source_name ORDER BY quantity_total DESC,c.source_name")->fetchAll();
  echo '<section class="panel form-panel"><div class="panel-header"><h2>خدمات کشف‌شده از بقراط</h2><span class="count">'.fa(count($srcServices)).'</span></div><p class="hint">فهرست فقط از سوابق واردشده ساخته شده و خدمات داخلی مسیحا را تغییر نمی‌دهد.</p><div class="table-scroll"><table><thead><tr><th>خدمت بقراط</th><th>دفعات</th><th>کمترین مبلغ</th><th>بیشترین مبلغ</th><th>خدمت داخلی مسیحا</th><th>تعرفه جاری</th></tr></thead><tbody>';
  foreach($srcServices as $v)echo '<tr><td>'.e($v['source_name']).'</td><td>'.fa($v['uses_count']).'</td><td>'.($v['min_price']===null?'—':money($v['min_price'])).'</td><td>'.($v['max_price']===null?'—':money($v['max_price'])).'</td><td>'.($v['service_id']?'<a href="/services?id='.(int)$v['service_id'].'#edit">'.e($v['mapped_name']).'</a>':'—').'</td><td>'.($v['service_id']?money($v['mapped_price']):'—').'</td></tr>';
  echo '</tbody></table></div></section>';
  echo '<section class="panel form-panel"><div class="panel-header"><h2>کالاهای کشف‌شده از بقراط</h2><span class="count">'.fa(count($srcGoods)).'</span></div><div class="table-scroll"><table><thead><tr><th>کالا</th><th>دفعات</th><th>تعداد کل</th><th>کمترین مبلغ</th><th>بیشترین مبلغ</th></tr></thead><tbody>';
  foreach($srcGoods as $v)echo '<tr><td>'.e($v['source_name']).'</td><td>'.fa($v['uses_count']).'</td><td>'.fa(rtrim(rtrim(number_format((float)$v['quantity_total'],3,'.',''),'0'),'.')).'</td><td>'.($v['min_price']===null?'—':money($v['min_price'])).'</td><td>'.($v['max_price']===null?'—':money($v['max_price'])).'</td></tr>';
  echo '</tbody></table></div></section>';
 }
 elseif($tab==='categories'){$r=$id?q('SELECT * FROM service_categories WHERE id=? AND deleted=0',[$id])->fetch():null;echo '<section class="panel form-panel">';foreach(q('SELECT * FROM service_categories WHERE deleted=0')->fetchAll() as $v){echo '<div class="resource-row"><strong>'.e($v['name']).'</strong><span>'.($v['active']?'فعال':'غیرفعال').'</span><a href="?tab=categories&id='.$v['id'].'">ویرایش</a>';deleteButton('category_delete',$v['id']);echo '</div>';}formstart('category_save');hidden('id',$id);field('name','نام دسته',$r['name']??'','text','دسته‌بندی خدمات کلینیک.',true);check('active','فعال',$r['active']??true);formend('ذخیره دسته','/services?tab=categories');echo '</section>';}
 elseif($tab==='packages'){$r=$id?q('SELECT * FROM packages WHERE id=? AND deleted=0',[$id])->fetch():null;$items=$id?array_column(q('SELECT * FROM package_items WHERE package_id=?',[$id])->fetchAll(),'quantity','service_id'):[];echo '<section class="panel form-panel">';foreach(q('SELECT * FROM packages WHERE deleted=0')->fetchAll() as $v){echo '<div class="resource-row"><div><strong>'.e($v['name']).'</strong><small>'.money($v['price']).' تومان · '.($v['auto_price']?'قیمت خودکار':'قیمت اختصاصی').' · '.($v['active']?'فعال':'غیرفعال').'</small></div><a href="?tab=packages&id='.$v['id'].'">ویرایش</a>';deleteButton('package_delete',$v['id']);echo '</div>';}echo '</section><section class="panel form-panel">';sectiontitle($id?'ویرایش پکیج':'پکیج جدید');formstart('package_save');hidden('id',$id);field('name','نام پکیج',$r['name']??'','text','عنوان بسته خدمات.',true);echo '<div class="package-items">';foreach(q('SELECT * FROM services WHERE deleted=0 ORDER BY name')->fetchAll() as $s)field('qty['.$s['id'].']',$s['name'].' · '.money($s['price']).' تومان',$items[$s['id']]??0,'number','تعداد این خدمت در پکیج؛ صفر یعنی خارج از پکیج.',false,false,'min="0" max="365" data-package-price="'.(int)$s['price'].'"');echo '</div><p class="notice" data-package-total>جمع خدمات: —</p>';check('auto_price','قیمت برابر جمع خدمات و به‌روزرسانی خودکار با تعرفه‌ها',$r['auto_price']??true);field('price','قیمت اختصاصی پکیج (تومان)',$r['price']??0,'number','فقط وقتی قیمت خودکار غیرفعال باشد اعمال می‌شود.',false,false,'min="0"');check('active','پکیج فعال',$r['active']??true);formend('ذخیره پکیج','/services?tab=packages');echo '</section>';}
 elseif($tab==='shares'){echo '<section class="panel form-panel">';sectiontitle('تعریف خدمت برای همکار');formstart('share_save');echo '<div class="form-grid">';selectfield('service_id','خدمت',options('services','deleted=0'),$id,'خدمت قابل ارائه توسط این همکار.',true);selectfield('staff_id','همکار / درمانگر',options('staff','deleted=0 AND active=1'),0,'همکار ارائه‌دهنده خدمت.',true);selectfield('share_type','نوع سهم',['percent'=>'درصد','fixed'=>'مبلغ ثابت'],'percent','سهم درمانگر از تعرفه هر جلسه.');field('share_value','مقدار سهم',0,'number','درصد از صفر تا ۱۰۰ یا مبلغ ثابت به تومان.',true,false,'min="0" step="0.01"');echo '</div>';formend('ذخیره یا ویرایش سهم','/services?tab=shares');echo '</section><section class="panel form-panel">';foreach(q('SELECT x.*,s.name service,u.name staff FROM service_staff x JOIN services s ON s.id=x.service_id JOIN staff u ON u.id=x.staff_id WHERE s.deleted=0 AND u.deleted=0')->fetchAll() as $v){echo '<div class="resource-row"><div><strong>'.e($v['staff']).' — '.e($v['service']).'</strong><small>'.money($v['share_value']).($v['share_type']==='percent'?' درصد':' تومان').'</small></div>';formstart('share_delete');hidden('service_id',$v['service_id']);hidden('staff_id',$v['staff_id']);echo '<button class="button secondary small" data-confirm="حذف تخصیص خدمت به همکار؟">حذف تخصیص</button></form></div>';}echo '<p class="hint">برای ویرایش سهم، همان خدمت و همکار را انتخاب و مقدار جدید را ذخیره کنید. سهم جلسات قبلی تغییر نمی‌کند.</p></section>';}
 else{$r=$id?q('SELECT * FROM services WHERE id=? AND deleted=0',[$id])->fetch():null;echo '<section class="panel"><div class="table-scroll"><table><thead><tr><th>خدمت</th><th>دسته</th><th>تعرفه (تومان)</th><th>مدت</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>';foreach(q('SELECT s.*,c.name category FROM services s LEFT JOIN service_categories c ON c.id=s.category_id WHERE s.deleted=0 ORDER BY s.id DESC')->fetchAll() as $v){echo '<tr><td>'.e($v['name']).'</td><td>'.e($v['category']??'—').'</td><td>'.money($v['price']).'</td><td>'.fa($v['duration']).' دقیقه</td><td>'.($v['active']?'فعال':'غیرفعال').'</td><td><div class="actions"><a href="?id='.$v['id'].'#edit">ویرایش</a><a href="?tab=shares&id='.$v['id'].'">سهم پزشک</a>';deleteButton('service_delete',$v['id']);echo '</div></td></tr>';}echo '</tbody></table></div></section><section class="panel form-panel" id="edit">';sectiontitle($id?'ویرایش خدمت':'ساخت خدمت');formstart('service_save');hidden('id',$id);echo '<div class="form-grid">';field('name','عنوان خدمت',$r['name']??'','text','نام خدمت در نوبت و گزارش.',true);selectfield('category_id','دسته‌بندی',options('service_categories','deleted=0'),$r['category_id']??0,'گروه خدمت.');field('price','تعرفه (تومان)',$r['price']??0,'number','برای حذف تعرفه، مبلغ صفر ثبت کنید. تغییر تعرفه روی جلسات قبلی اثر ندارد.',true,false,'min="0"');field('duration','مدت پیش‌فرض (دقیقه)',$r['duration']??30,'number','مدت پیشنهادی در نوبت‌دهی.',true,false,'min="5" max="480"');echo '</div>';check('active','خدمت فعال',$r['active']??true);formend('ذخیره خدمت','/services');echo '</section>';}endLayout();}
function smsView():void{
 need('sms');$cfg=MasihaSms::config();$enabled=MasihaSms::enabled();$templates=q('SELECT * FROM sms_templates ORDER BY id')->fetchAll();
 $stats=[];foreach(q("SELECT status,COUNT(*) c FROM sms_outbox GROUP BY status")->fetchAll() as $r)$stats[$r['status']]=$r['c'];
 layout('sms','پنل پیامک','قالب‌ها، صف ارسال، یادآوری‌ها و گزارش پیام‌های کلینیک.');
 echo '<div class="stats-grid three">';
 foreach(['queued'=>'در صف','sent'=>'ارسال‌شده','failed'=>'ناموفق','cancelled'=>'لغوشده'] as $k=>$label)echo '<article class="stat-card"><span>'.$label.'</span><strong>'.fa((int)($stats[$k]??0)).'</strong></article>';
 echo '</div>';

 echo '<section class="panel form-panel"><div class="panel-header"><div><h2>اتصال و ارسال خودکار</h2><p class="muted">کلید کاوه‌نگار در فایل امن تنظیمات نگهداری می‌شود و در این صفحه نمایش داده نمی‌شود.</p></div><span class="badge '.($enabled?'active':'').'">'.($enabled?'فعال':'غیرفعال').'</span></div>';
 formstart('sms_config');
 echo '<div class="form-grid">';
 field('sms_sender','شماره فرستنده',$cfg['sender']??'','text','اختیاری؛ خط خدماتی/تبلیغاتی ثبت‌شده در کاوه‌نگار.');
 echo '<div class="field"><label>وضعیت کلید API</label><div class="notice">'.(!empty($cfg['key'])?'کلید اتصال ثبت شده است.':'کلید اتصال ثبت نشده؛ از تنظیمات کلینیک وارد کنید.').'</div></div></div>';
 check('sms_notifications','فعال‌کردن ارسال پیامک‌های کلینیک',$enabled);
 echo '<p class="hint">تا وقتی این گزینه خاموش است، هیچ پیام خودکار یا گروهی ارسال نمی‌شود. قالب‌ها نیز جداگانه باید فعال شوند.</p>';
 formend('ذخیره تنظیمات پیامک','/sms');
 echo '</section>';

 echo '<section class="panel form-panel" id="templates"><div class="panel-header"><h2>قالب‌های خودکار</h2><span class="count">'.fa(count($templates)).'</span></div><p class="hint">متغیرهای قابل استفاده: {patient_name}، {first_name}، {clinic_name}، {clinic_phone}، {date}، {time}، {therapist}، {service}، {clinic}</p>';
 foreach($templates as $t){
  formstart('sms_template_save');hidden('event_key',$t['event_key']);
  echo '<details '.($t['enabled']?'open':'').'><summary><strong>'.e($t['title']).'</strong> · '.($t['enabled']?'فعال':'غیرفعال').'</summary><div class="form-grid">';
  field('message_template','متن پیام',$t['message_template'],'textarea','حداکثر ۲۰۰۰ نویسه.',true,true);
  if($t['event_key']==='appointment_reminder')field('send_offset_minutes','چند دقیقه قبل از نوبت',$t['send_offset_minutes'],'number','مثلاً ۱۴۴۰ یعنی یک روز قبل.',true,false,'min="0" max="10080"');
  else hidden('send_offset_minutes',0);
  echo '</div>';check('enabled','این قالب فعال باشد',(bool)$t['enabled']);echo '<div class="form-actions"><button class="button primary" type="submit">ذخیره قالب</button></div></details></form>';
 }
 echo '</section>';

 echo '<section class="panel form-panel"><div class="panel-header"><h2>ارسال گروهی</h2><span class="muted">ارسال فقط پس از قرارگرفتن در صف انجام می‌شود.</span></div>';
 formstart('sms_campaign_queue');echo '<div class="form-grid">';
 field('title','عنوان داخلی','','text','فقط برای گزارش داخلی است.',true);
 selectfield('audience','دریافت‌کنندگان',['all_active'=>'تمام بیماران فعال','portal'=>'بیماران دارای پورتال فعال','debtors'=>'بیماران دارای مانده بدهی'],'portal','فقط پرونده‌های دارای موبایل معتبر وارد صف می‌شوند.',true);
 field('message','متن پیام','','textarea','متن دقیق پیام گروهی.',true,true);
 echo '</div>';formend('قرار دادن در صف','/sms');echo '</section>';

 $rows=q("SELECT o.*,p.fname,p.lname FROM sms_outbox o LEFT JOIN patients p ON p.pid=o.pid ORDER BY o.id DESC LIMIT 200")->fetchAll();
 echo '<section class="panel"><div class="panel-header"><div><h2>تاریخچه و صف پیامک</h2><p class="muted">آخرین ۲۰۰ پیام</p></div><form method="post">';csrf();echo '<input type="hidden" name="action" value="sms_process"><button class="button secondary" '.(!$enabled?'disabled':'').'>پردازش ۲۰ پیام</button></form></div>';
 if(!$rows)emptyState('هنوز پیامکی در صف نیست','پس از فعال‌سازی قالب‌ها یا ثبت ارسال گروهی، پیام‌ها اینجا دیده می‌شوند.');
 else{echo '<div class="table-scroll"><table><thead><tr><th>زمان</th><th>بیمار</th><th>نوع</th><th>گیرنده</th><th>وضعیت</th><th>تلاش</th><th>خطا</th><th></th></tr></thead><tbody>';$labels=['queued'=>'در صف','sending'=>'در حال ارسال','sent'=>'ارسال‌شده','failed'=>'ناموفق','cancelled'=>'لغوشده'];foreach($rows as $r){echo '<tr><td>'.jd($r['scheduled_at'],'yyyy/MM/dd HH:mm').'</td><td>'.($r['pid']?'<a href="/patient?id='.(int)$r['pid'].'">'.e(trim(($r['fname']??'').' '.($r['lname']??''))).'</a>':'—').'</td><td>'.e($r['event_key']).'</td><td>'.fa($r['mobile']).'</td><td>'.e($labels[$r['status']]??$r['status']).'</td><td>'.fa($r['attempts']).'</td><td>'.e($r['last_error']?:'—').'</td><td><div class="actions">';if(in_array($r['status'],['failed','cancelled'],true)){echo '<form method="post">';csrf();echo '<input type="hidden" name="action" value="sms_retry"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="button secondary small">تلاش مجدد</button></form>';}if(in_array($r['status'],['queued','failed'],true)){echo '<form method="post">';csrf();echo '<input type="hidden" name="action" value="sms_cancel"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="button secondary small">لغو</button></form>';}echo '</div></td></tr>';}echo '</tbody></table></div>';}
 echo '</section>';
 endLayout();
}

function appearanceView():void{need('settings');$id=(int)($_GET['id']??0);$r=$id?q('SELECT * FROM clinics WHERE id=?',[$id])->fetch():null;layout('settings','ظاهر و کلینیک‌ها','رنگ و فونت دلخواه و معرفی محل‌های ارائه خدمت.');echo '<div class="dashboard-grid"><section class="panel form-panel">';sectiontitle('ظاهر سامانه');formstart('appearance');field('theme_color','رنگ اصلی',setting('theme_color','#087f75'),'color','رنگ دکمه‌ها و اجزای اصلی سامانه.',true);$fonts=['0'=>'وزیرمتن (پیش‌فرض)']+array_column(q('SELECT * FROM custom_fonts')->fetchAll(),'name','id');selectfield('font_id','فونت متن',$fonts,setting('font_id','0'),'فونت فرم‌ها و متن‌های سامانه.');selectfield('heading_font_id','فونت عنوان‌ها',$fonts,setting('heading_font_id','0'),'امکان انتخاب فونت جداگانه برای عنوان‌ها.');formend('ذخیره ظاهر','/settings');echo '</section><section class="panel form-panel">';sectiontitle('بارگذاری فونت');formstart('font_upload',true);field('name','نام فونت','','text','نامی برای انتخاب از فهرست فونت‌ها.',true);field('font','فایل فونت','','file','فرمت WOFF یا WOFF2، حداکثر ۳ مگابایت.',true,false,'accept=".woff,.woff2"');formend('بارگذاری فونت','/appearance');echo '</section></div><section class="panel form-panel">';sectiontitle('کلینیک‌ها','محل مراجعه هنگام ثبت نوبت انتخاب می‌شود. حساب‌ها و گزارش‌ها در این سامانه مشترک‌اند.');foreach(q('SELECT * FROM clinics')->fetchAll() as $v)echo '<div class="resource-row"><strong>'.e($v['name']).'</strong><span>'.e($v['phone']).' · '.($v['active']?'فعال':'غیرفعال').'</span><a href="?id='.$v['id'].'">ویرایش</a></div>';formstart('clinic_save');hidden('id',$id);echo '<div class="form-grid">';field('name','نام کلینیک',$r['name']??'','text','نام محل ارائه خدمت.',true);field('phone','تلفن',$r['phone']??'','tel','شماره تماس پذیرش این محل.');field('address','نشانی',$r['address']??'','textarea','نشانی مراجعه حضوری.',false,true);echo '</div>';check('active','کلینیک فعال',$r['active']??true);formend('ذخیره کلینیک','/appearance');echo '</section>';endLayout();}
function liveSearch($picker=false):void{?><div class="live-search" data-live-search <?=$picker?'data-picker':''?>><label>جستجوی مراجعه <?=icon('search')?></label><input type="search" autocomplete="off" placeholder="کد ملی، شماره تلفن، نام یا نام خانوادگی" aria-label="جستجوی زنده مراجعه"><div class="live-results" role="status" hidden></div></div><?php }
function bookingView():void{need('appointments');layout('appointments','ثبت نوبت','مراجعه را پیدا کنید، درمانگر و زمان را انتخاب کنید.');formstart('book_v2');echo '<div class="form-layout"><section class="panel form-panel">';sectiontitle('۱. انتخاب مراجعه');liveSearch(true);$pid=(int)($_GET['pid']??0);if($pid)requirePatient($pid);hidden('pid',$pid);echo '<p id="selected-patient" class="notice">'.($pid?e(patientName(q('SELECT * FROM patients WHERE pid=?',[$pid])->fetch())):'هنوز مراجعه‌ای انتخاب نشده است.').'</p>';if(allowed('patients.create'))echo '<a class="button secondary" href="/patients/new?next=booking">ثبت مراجعه جدید +</a>';sectiontitle('۲. مشخصات نوبت');echo '<div class="form-grid">';selectfield('therapist_id','درمانگر',therapists(),'','درمانگر ارائه‌دهنده خدمت.',true);selectfield('service_id','خدمت',['0'=>'ویزیت بدون خدمت مشخص'],'0','فقط خدمات تعریف‌شده برای درمانگر انتخابی نشان داده می‌شوند.');selectfield('tariff_id','تعرفه',['0'=>'تعرفه جاری خدمت'],'0','تعرفه‌های عادی و قراردادی معتبر برای تاریخ مراجعه نمایش داده می‌شوند.');selectfield('episode_id','دوره درمان',['0'=>'ویزیت جدید (ایجاد خودکار دوره تک‌جلسه‌ای)'],0,'می‌توانید این نوبت را به یک دوره فعال بیمار متصل کنید.');selectfield('clinic_id','محل مراجعه',options('clinics','active=1'),1,'کلینیکی که بیمار به آن مراجعه می‌کند.',true);selectfield('label_id','لیبل',['0'=>'انتخاب خودکار از پرونده یا پیش‌فرض']+array_column(q('SELECT id,name FROM labels WHERE active=1 AND deleted=0')->fetchAll(),'name','id'),0,'انتخاب دستی بر لیبل خودکار اولویت دارد.');field('duration','مدت ویزیت (دقیقه)',30,'number','مدت اشغال زمان درمانگر؛ بین ۵ و ۴۸۰ دقیقه.',true,false,'min="5" max="480"');field('date','تاریخ مراجعه',preg_match('/^\d{4}-\d{2}-\d{2}$/D',(string)($_GET['date']??''))?$_GET['date']:date('Y-m-d'),'date','ماه جاری و چهار ماه بعد از داخل تقویم قابل انتخاب‌اند.',true);field('time','ساعت مراجعه','09:00','time','ساعت شروع مراجعه با قالب ۲۴ ساعته.',true);selectfield('room','اتاق',[''=>'بدون اتاق اختصاصی']+array_column(q("SELECT name FROM resources WHERE kind='room' AND active=1")->fetchAll(),'name','name'),'','اختیاری؛ در صورت انتخاب، تداخل اتاق بررسی می‌شود.');field('notes','یادداشت','','textarea','توضیحات لازم برای پذیرش و درمانگر.',false,true);hidden('equipment','');echo '</div></section><aside><section class="info-card"><h2>نوبت‌دهی ساده و دقیق</h2><p>اطلاعات زمان به میلادی ذخیره می‌شوند و تقویم و تاریخ‌های نمایشی شمسی هستند.</p><p>تداخل درمانگر و بیمار پیش از ثبت بررسی می‌شود.</p></section></aside></div>';formend('ثبت نوبت','/appointments');endLayout();}
function formsView():void{
 need('forms');$pid=(int)($_GET['pid']??0);$id=(int)($_GET['id']??0);$sourceSubmission=(int)($_GET['source_submission']??0);
 if($sourceSubmission){
  if(scope('forms.general')!=='all'){http_response_code(403);exit('به فرم‌های واردشده دسترسی ندارید.');}
  $src=q("SELECT s.*,t.title,p.fname,p.lname FROM clinic_form_submissions s JOIN clinic_form_templates t ON t.id=s.template_id JOIN patients p ON p.pid=s.pid WHERE s.id=? AND s.source_system='boghrat'",[$sourceSubmission])->fetch();
  if(!$src){http_response_code(404);exit('فرم پیدا نشد.');}
  requirePatient((int)$src['pid']);
  layout('forms',$src['title'],'فرم ساختاریافته منتقل‌شده از بقراط؛ این نسخه فقط خواندنی است.');
  echo '<section class="panel form-panel"><div class="panel-header"><div><h2>'.e($src['title']).'</h2><p class="muted">'.e(patientName($src)).' · تاریخ ثبت: '.($src['source_submitted_jalali']?fa($src['source_submitted_jalali']):'ثبت نشده').'</p></div><span class="badge">بقراط</span></div><dl class="detail-list">';
  foreach(q("SELECT f.label,f.field_type,v.value_text FROM clinic_form_submission_values v JOIN clinic_form_template_fields f ON f.id=v.field_id WHERE v.submission_id=? ORDER BY f.sort_order,f.id",[$sourceSubmission])->fetchAll() as $v)echo '<dt>'.e($v['label']).'</dt><dd>'.e($v['value_text']!==''?$v['value_text']:'ثبت نشده').'</dd>';
  echo '</dl><div class="form-actions"><a class="button secondary" href="/forms?pid='.(int)$src['pid'].'">بازگشت به فرم‌های مراجعه</a><a class="button secondary" href="/patient?id='.(int)$src['pid'].'">پرونده بیمار</a></div></section>';endLayout();return;
 }
 $r=$id?q('SELECT * FROM clinic_forms WHERE id=? AND deleted=0',[$id])->fetch():null;
 if($r){$pid=(int)$r['pid'];if(scope('forms.'.$r['kind'])==='none'||(scope('forms.'.$r['kind'])==='own'&&(int)$r['created_by']!==(int)user()['id'])){http_response_code(403);exit;}}
 if($pid)requirePatient($pid);
 layout('forms','فرم‌های مراجعه','فرم‌های دستی مسیحا و فرم‌های ساختاریافته منتقل‌شده از بقراط.');
 echo '<section class="panel form-panel"><div class="panel-header"><h2>فرم‌های مسیحا</h2></div>';
 foreach(q("SELECT f.*,p.fname,p.lname FROM clinic_forms f JOIN patients p ON p.pid=f.pid WHERE f.deleted=0 AND ".patientScope()." AND ((f.kind='visit' AND ".formScope('f','visit').") OR (f.kind='general' AND ".formScope('f','general')."))".($pid?' AND f.pid='.(int)$pid:'').' ORDER BY f.id DESC LIMIT 200')->fetchAll() as $v)echo '<div class="resource-row"><div><strong>'.e($v['title']).'</strong><small>'.e(patientName($v)).' · '.jd($v['created_at']).'</small></div><a href="?id='.$v['id'].'">مشاهده / ویرایش</a></div>';
 echo '</section>';
 if(scope('forms.general')==='all'){
  $sourceRows=q("SELECT s.id,s.pid,s.source_submitted_jalali,s.source_submitted_date,t.title,p.fname,p.lname FROM clinic_form_submissions s JOIN clinic_form_templates t ON t.id=s.template_id JOIN patients p ON p.pid=s.pid WHERE s.source_system='boghrat' AND ".patientScope('p').($pid?' AND s.pid='.(int)$pid:'')." ORDER BY COALESCE(s.source_submitted_date,'1000-01-01') DESC,s.id DESC LIMIT 200")->fetchAll();
  echo '<section class="panel form-panel"><div class="panel-header"><h2>فرم‌های ساختاریافته بقراط</h2><span class="count">'.fa(count($sourceRows)).'</span></div><p class="hint">پاسخ‌ها به‌صورت فیلدهای مستقل ذخیره شده‌اند و آرشیو خام منبع جداگانه محفوظ است.</p>';
  foreach($sourceRows as $v)echo '<div class="resource-row"><div><strong>'.e($v['title']).'</strong><small>'.e(patientName($v)).' · '.($v['source_submitted_jalali']?fa($v['source_submitted_jalali']):'تاریخ نامشخص').'</small></div><a href="/forms?source_submission='.(int)$v['id'].'">مشاهده پاسخ‌ها</a></div>';
  echo '</section>';
 }
 echo '<section class="panel form-panel">';formstart('form_save');hidden('id',$id);$ps=[''=>'انتخاب مراجعه'];foreach(q('SELECT p.pid,p.fname,p.lname FROM patients p WHERE p.active=1 AND '.patientScope().' ORDER BY p.lname')->fetchAll() as $p)$ps[$p['pid']]=patientName($p);selectfield('pid','مراجعه',$ps,$pid,'فقط مراجعین مجاز قابل انتخاب‌اند.',true);$kinds=[];foreach(['visit'=>'ویزیت','general'=>'عمومی'] as $k=>$title)if(scope('forms.'.$k)!=='none')$kinds[$k]=$title;selectfield('kind','نوع فرم',$kinds,$r['kind']??'general','نوع فرم تعیین‌کننده مجوز مشاهده و ویرایش است.',true);field('title','عنوان فرم',$r['title']??'','text','مانند رضایت‌نامه یا ارزیابی ویزیت.',true);field('body','محتوای فرم',$r['body']??'','textarea','متن فرم و اطلاعات ثبت‌شده برای مراجعه.',true,true);formend('ذخیره فرم','/forms');if($id)deleteButton('form_delete',$id,'بایگانی فرم');echo '</section>';endLayout();
}
function financeFilters():array{$from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-d'));foreach([$from,$to] as $v){$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new DomainException('تاریخ گزارش معتبر نیست.');}if($from>$to)throw new DomainException('بازه تاریخ معتبر نیست.');$tid=max(0,(int)($_GET['therapist']??0));$clinic=max(0,(int)($_GET['clinic']??0));$where='1=1';if($tid||$clinic)$where='EXISTS(SELECT 1 FROM physio_sessions fs WHERE fs.episode_id=e.id'.($tid?' AND fs.therapist_id='.$tid:'').($clinic?' AND fs.clinic_id='.$clinic:'').')';return [$from,$to,$where,$tid,$clinic];}
function financeV2($report=false):void{need($report?'reports':'finance');[$from,$to,$where,$tid,$clinic]=financeFilters();$canHistory=allowed('finance.history')||$report;$canDebt=allowed('finance.debt')||$report;$page=max(1,(int)($_GET['p']??1));$paywhere="x.voided=0 AND x.created_at>=? AND x.created_at<DATE_ADD(?,INTERVAL 1 DAY) AND $where";$args=[$from,$to];
 if($report&&($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="clinic-finance.csv"');echo "\xEF\xBB\xBF";$f=fopen('php://output','w');fputcsv($f,['شناسه','تاریخ شمسی','بیمار','مبلغ تومان','پیگیری','ثبت‌کننده']);$st=q("SELECT x.*,p.fname,p.lname,u.name actor FROM physio_payments x JOIN physio_episodes e ON e.id=x.episode_id JOIN patients p ON p.pid=e.pid LEFT JOIN staff u ON u.id=x.created_by WHERE $paywhere ORDER BY x.created_at",$args);while($r=$st->fetch()){fputcsv($f,array_map(fn($v)=>preg_match('/^[=+@\-\t\r]/u',(string)$v)?"'".$v:$v,[$r['id'],jd($r['created_at'],'yyyy/MM/dd HH:mm'),patientName($r),$r['amount_toman'],$r['reference'],$r['actor']]));}fclose($f);exit;}
 layout($report?'reports':'finance',$report?'گزارش‌های مالی و عملکرد':'امور مالی','تمام مبالغ تومان است. دریافت وجه با درآمد تحقق‌یافته و ارزش خدمات تفاوت دارد.');echo '<section class="panel form-panel"><form method="get"><div class="form-grid three">';field('from','از تاریخ',$from,'date','بازه تراکنش‌ها و جلسات گزارش.',true);field('to','تا تاریخ',$to,'date','روز پایانی نیز در گزارش محاسبه می‌شود.',true);selectfield('therapist','درمانگر',['0'=>'همه درمانگران']+therapists(),$tid,'مالی: دوره‌های دارای جلسه با این درمانگر؛ سهم: فقط جلسات خود درمانگر.');selectfield('clinic','کلینیک',['0'=>'همه کلینیک‌ها']+options('clinics'),$clinic,'دوره‌های دارای جلسه در کلینیک انتخابی.');echo '</div><button class="button primary">نمایش گزارش</button>';if($report)echo ' <a class="button secondary" href="?'.e(http_build_query(['from'=>$from,'to'=>$to,'therapist'=>$tid,'clinic'=>$clinic,'export'=>'csv'])).'">دریافت CSV همه تراکنش‌ها</a>';echo '</form></section>';
 if($canHistory){$sum=q("SELECT COALESCE(SUM(IF(x.amount_toman>0,x.amount_toman,0)),0) incoming,COALESCE(SUM(IF(x.amount_toman<0,-x.amount_toman,0)),0) refunds FROM physio_payments x JOIN physio_episodes e ON e.id=x.episode_id WHERE $paywhere",$args)->fetch();echo '<div class="stats-grid three">';foreach(['دریافت در بازه'=>$sum['incoming'],'بازگشت وجه در بازه'=>$sum['refunds'],'خالص دریافت در بازه'=>$sum['incoming']-$sum['refunds']] as $k=>$v)echo '<article class="stat-card"><span>'.$k.'</span><strong>'.money($v).'</strong><small>تومان</small></article>';echo '</div>';}
 if($canHistory||$canDebt){
  $src=q("SELECT
    COALESCE(SUM(CASE WHEN t.tx_type='payment' THEN t.amount_toman ELSE 0 END),0) payments,
    COALESCE(SUM(CASE WHEN t.tx_type='service_charge' THEN t.amount_toman ELSE 0 END),0) charges,
    COALESCE(SUM(CASE WHEN t.tx_type='discount' THEN t.amount_toman ELSE 0 END),0) discounts
    FROM import_financial_transactions t
    WHERE t.is_snapshot=0 AND t.tx_date>=? AND t.tx_date<DATE_ADD(?,INTERVAL 1 DAY)",[$from,$to])->fetch();
  $sourceDebt=(int)q("SELECT COALESCE(SUM(x.balance),0) FROM (
      SELECT pid,GREATEST(SUM(debit_toman-credit_toman),0) balance
      FROM patient_account_ledger WHERE voided=0 GROUP BY pid
    ) x")->fetchColumn();
  echo '<section class="panel form-panel"><div class="panel-header"><h2>سوابق مالی تاریخی بقراط</h2><span class="muted">مستقل از اسناد مالی داخلی مسیحا</span></div><p class="hint">فیلتر تاریخ روی تراکنش‌های منبع اعمال می‌شود؛ فیلتر درمانگر/کلینیک داخلی روی این داده تاریخی اعمال نمی‌شود.</p><div class="stats-grid three">';
  foreach(['جمع هزینه مراجعه در بازه'=>$src['charges'],'پرداخت واقعی در بازه'=>$src['payments'],'تخفیف در بازه'=>$src['discounts'],'مانده افتتاحیه قابل پیگیری'=>$sourceDebt] as $k=>$v)echo '<article class="stat-card"><span>'.$k.'</span><strong>'.money($v).'</strong><small>تومان</small></article>';
  echo '</div>';
  if($canHistory){$sourceRows=q("SELECT t.*,p.pid,p.fname,p.lname,
      (SELECT GROUP_CONCAT(CONCAT(a.appointment_code,'|',a.amount_toman) ORDER BY a.event_no SEPARATOR ',') FROM import_financial_allocations a WHERE a.transaction_id=t.id) allocations
      FROM import_financial_transactions t
      JOIN import_records r ON r.id=t.record_id
      JOIN patients p ON p.pid=r.pid
      WHERE t.is_snapshot=0 AND t.tx_date>=? AND t.tx_date<DATE_ADD(?,INTERVAL 1 DAY)
      ORDER BY t.tx_date DESC,t.id DESC LIMIT 50",[$from,$to])->fetchAll();
    $labels=['service_charge'=>'جمع هزینه مراجعه','payment'=>'پرداخت','discount'=>'تخفیف'];
    echo '<div class="table-scroll"><table><thead><tr><th>تاریخ</th><th>بیمار</th><th>نوع</th><th>مبلغ</th><th>روش</th><th>کد نوبت</th></tr></thead><tbody>';
    foreach($sourceRows as $r){$appt=$r['appointment_code']?:'';if(!$appt&&!empty($r['allocations'])){$parts=[];foreach(explode(',',$r['allocations']) as $piece){[$code,$amount]=array_pad(explode('|',$piece,2),2,'');$parts[]=fa($code).' · '.money((int)$amount).' ت';}$appt=implode(' / ',$parts);}echo '<tr><td>'.jd($r['tx_date']).'</td><td><a href="/patient?id='.(int)$r['pid'].'">'.e(patientName($r)).'</a></td><td>'.e($labels[$r['tx_type']]??$r['tx_type']).'</td><td>'.money($r['amount_toman']).'</td><td>'.e($r['method']?:'—').'</td><td>'.($appt?:'—').'</td></tr>';}
    echo '</tbody></table></div>';
  }
  if($canDebt){$sourceDebts=q("SELECT p.pid,p.fname,p.lname,SUM(l.debit_toman-l.credit_toman) balance
      FROM patient_account_ledger l JOIN patients p ON p.pid=l.pid
      WHERE l.voided=0 GROUP BY p.pid,p.fname,p.lname
      HAVING balance>0 ORDER BY balance DESC LIMIT 50")->fetchAll();
    if($sourceDebts){echo '<h3>مانده افتتاحیه / قبلی قابل پیگیری</h3><div class="table-scroll"><table><thead><tr><th>بیمار</th><th>مانده بدهی</th></tr></thead><tbody>';foreach($sourceDebts as $r)echo '<tr><td><a href="/patient?id='.(int)$r['pid'].'">'.e(patientName($r)).'</a></td><td>'.money($r['balance']).'</td></tr>';echo '</tbody></table></div>';}
  }
  echo '</section>';
 }
 if(!$report&&allowed('finance.pay')){
  $legacyOptions=[''=>'انتخاب بیمار دارای مانده قبلی'];foreach(q("SELECT p.pid,p.fname,p.lname,SUM(l.debit_toman-l.credit_toman) balance FROM patient_account_ledger l JOIN patients p ON p.pid=l.pid WHERE l.voided=0 GROUP BY p.pid,p.fname,p.lname HAVING balance>0 ORDER BY p.lname,p.fname")->fetchAll() as $lp)$legacyOptions[$lp['pid']]=patientName($lp).' — مانده '.money($lp['balance']).' تومان';
  if(count($legacyOptions)>1){echo '<section class="panel form-panel">';sectiontitle('ثبت پرداخت مانده قبلی','برای تسویه مانده افتتاحیه منتقل‌شده از بقراط؛ این پرداخت به دوره درمان جدید متصل نمی‌شود.');formstart('legacy_balance_payment');echo '<div class="form-grid three">';selectfield('pid','بیمار',$legacyOptions,(int)($_GET['legacy_patient']??0),'فقط بیماران دارای مانده قبلی نمایش داده می‌شوند.',true);field('amount_toman','مبلغ پرداخت (تومان)','','number','حداکثر تا مانده قبلی بیمار.',true,false,'min="1"');field('reference','پیگیری / توضیح','','text','روش پرداخت یا شماره پیگیری.');echo '</div>';formend('ثبت پرداخت مانده قبلی','/finance');echo '</section>';}
 }
 $eps=q("SELECT e.id,e.diagnosis,e.fee_toman,p.fname,p.lname,COALESCE((SELECT SUM(amount_toman) FROM physio_payments px WHERE px.episode_id=e.id AND px.voided=0),0) paid FROM physio_episodes e JOIN patients p ON p.pid=e.pid WHERE $where ORDER BY e.id DESC LIMIT 50 OFFSET ".(($page-1)*50))->fetchAll();
 if($canDebt){$debts=q("SELECT COALESCE(SUM(GREATEST(e.fee_toman-COALESCE((SELECT SUM(amount_toman) FROM physio_payments px WHERE px.episode_id=e.id AND px.voided=0),0),0)),0) debt FROM physio_episodes e WHERE $where")->fetchColumn();$legacyDebt=(int)q("SELECT COALESCE(SUM(x.balance),0) FROM (SELECT pid,GREATEST(SUM(debit_toman-credit_toman),0) balance FROM patient_account_ledger WHERE voided=0 GROUP BY pid) x")->fetchColumn();echo '<section class="panel form-panel"><h2>بدهی جاری: '.money($debts+$legacyDebt).' تومان</h2><p class="hint">دوره‌های مسیحا: '.money($debts).' تومان · مانده قبلی/افتتاحیه: '.money($legacyDebt).' تومان.</p><div class="table-scroll"><table><thead><tr><th>بیمار / دوره</th><th>بدهی فعلی</th></tr></thead><tbody>';foreach($eps as $ep)echo '<tr><td>'.e(patientName($ep)).'<small>'.e($ep['diagnosis']).'</small></td><td>'.money(max(0,$ep['fee_toman']-$ep['paid'])).'</td></tr>';echo '</tbody></table></div><div class="pagination">';if($page>1)echo '<a href="?'.e(http_build_query(array_merge($_GET,['p'=>$page-1]))).'">صفحه قبل</a>';if(count($eps)===50)echo '<a href="?'.e(http_build_query(array_merge($_GET,['p'=>$page+1]))).'">صفحه بعد</a>';echo '</div></section>';}
 $epopts=[''=>'انتخاب دوره'];if(!$report&&(allowed('finance.pay')||allowed('finance.referral')||allowed('finance.edit')))foreach(q('SELECT e.id,e.diagnosis,p.fname,p.lname FROM physio_episodes e JOIN patients p ON p.pid=e.pid ORDER BY e.id DESC')->fetchAll() as $ep)$epopts[$ep['id']]=patientName($ep).' — '.$ep['diagnosis'];
 if(!$report&&allowed('finance.pay')){echo '<section class="panel form-panel">';sectiontitle('ثبت دریافت / بازگشت وجه');formstart('payment');$nonce=bin2hex(random_bytes(16));$_SESSION['payments'][$nonce]=time();$_SESSION['payments']=array_slice($_SESSION['payments'],-20,null,true);hidden('payment_nonce',$nonce);echo '<div class="form-grid three">';selectfield('episode_id','دوره',$epopts,$_GET['episode']??'','دوره مرتبط با تراکنش.',true);field('amount_toman','مبلغ (تومان)','','number','مثبت: دریافت؛ منفی: بازگشت وجه تا سقف دریافتی.',true);field('reference','پیگیری / توضیح','','text','کد پیگیری یا روش پرداخت.');echo '</div>';formend('ثبت تراکنش','/finance');echo '</section>';}
 if($canHistory){$ps=q("SELECT x.*,p.fname,p.lname,u.name actor FROM physio_payments x JOIN physio_episodes e ON e.id=x.episode_id JOIN patients p ON p.pid=e.pid LEFT JOIN staff u ON u.id=x.created_by WHERE $paywhere ORDER BY x.id DESC LIMIT 50 OFFSET ".(($page-1)*50),$args)->fetchAll();echo '<section class="panel form-panel"><h2>تراکنش‌های بازه</h2><div class="table-scroll"><table><thead><tr><th>تاریخ</th><th>بیمار</th><th>مبلغ</th><th>پیگیری</th><th>ثبت‌کننده</th><th>عملیات</th></tr></thead><tbody>';foreach($ps as $r){echo '<tr><td>'.jd($r['created_at'],'yyyy/MM/dd HH:mm').'</td><td>'.e(patientName($r)).'</td><td>'.money($r['amount_toman']).'</td><td>'.e($r['reference']).'</td><td>'.e($r['actor']).'</td><td>';if(allowed('finance.edit')||allowed('finance.delete'))echo '<a href="/finance?edit='.$r['id'].'">اصلاح / ابطال</a>';echo '</td></tr>';}echo '</tbody></table></div><div class="pagination">';if($page>1)echo '<a href="?'.e(http_build_query(array_merge($_GET,['p'=>$page-1]))).'">صفحه قبل</a>';if(count($ps)===50)echo '<a href="?'.e(http_build_query(array_merge($_GET,['p'=>$page+1]))).'">صفحه بعد</a>';echo '</div></section>';}
 if(!$report&&isset($_GET['edit'])){$r=q('SELECT * FROM physio_payments WHERE id=? AND voided=0',[(int)$_GET['edit']])->fetch();if($r){echo '<section class="panel form-panel">';sectiontitle('اصلاح مالی با حفظ سابقه');foreach(['payment_edit'=>'ویرایش مبلغ','payment_void'=>'ابطال تراکنش'] as $a=>$title)if(allowed($a==='payment_edit'?'finance.edit':'finance.delete')){formstart($a);hidden('id',$r['id']);if($a==='payment_edit')field('amount_toman','مبلغ اصلاح‌شده',$r['amount_toman'],'number','مبلغ جدید تراکنش.',true);field('reason','دلیل اصلاح','','text','در سابقه تغییرات مالی ثبت می‌شود.',true);formend($title,'/finance');}echo '</section>';}}
 if(!$report&&allowed('finance.edit')){echo '<section class="panel form-panel">';sectiontitle('ویرایش مبلغ دوره');formstart('fee_edit');selectfield('episode_id','دوره',$epopts,'','دوره مورد نظر.',true);field('fee_toman','مبلغ جدید دوره','','number','مبلغ کل توافق‌شده دوره.',true,false,'min="0"');formend('ویرایش مبلغ','/finance');echo '</section>';}
 if(!$report&&allowed('finance.referral')){echo '<section class="panel form-panel">';sectiontitle('تعیین سهم معرفی بیمار');formstart('referral_save');echo '<div class="form-grid">';selectfield('episode_id','دوره',$epopts,'','درصد از مبلغ کل دوره محاسبه می‌شود.',true);field('recipient','معرف / دریافت‌کننده سهم','','text','نام شخص یا مرکز معرفی‌کننده.',true);selectfield('kind','نوع سهم',['percent'=>'درصد مبلغ دوره','fixed'=>'مبلغ ثابت'],'percent','مبنای محاسبه سهم معرفی.');field('value','مقدار سهم',0,'number','درصد تا ۱۰۰ یا مبلغ ثابت تومان.',true,false,'min="0" step="0.01"');echo '</div>';formend('ثبت سهم معرفی','/finance');echo '</section>';}
 if($report){
  $historicalWhere='e.event_date>=? AND e.event_date<DATE_ADD(?,INTERVAL 1 DAY)'.($tid?' AND e.therapist_id='.(int)$tid:'');
  $historicalArgs=[$from,$to];
  $historical=q("SELECT COALESCE(s.name,e.practitioner,'بدون درمانگر') therapist,COUNT(*) visits,COUNT(DISTINCT r.pid) patients,
      SUM(e.status_code='done') done_count,SUM(e.status_code='absent') absent_count,SUM(e.status_code='cancelled') cancelled_count,
      SUM(COALESCE(e.charge_total_toman,0)) charge_total
    FROM import_patient_events e
    JOIN import_records r ON r.id=e.record_id
    LEFT JOIN staff s ON s.id=e.therapist_id
    WHERE $historicalWhere
    GROUP BY e.therapist_id,s.name,e.practitioner
    ORDER BY visits DESC,therapist",$historicalArgs)->fetchAll();
  echo '<section class="panel form-panel"><div class="panel-header"><h2>عملکرد تاریخی درمانگران بقراط</h2><span class="muted">از داده ساختاریافته واردشده</span></div><p class="hint">فیلتر درمانگر روی شناسه داخلی مسیحا اعمال می‌شود. فیلتر کلینیک برای سوابق قدیمی بقراط قابل اعمال نیست چون کلینیک در هر ویزیت تاریخی به‌صورت مستقل ذخیره نشده است.</p><div class="table-scroll"><table><thead><tr><th>درمانگر</th><th>مراجع یکتا</th><th>کل ویزیت</th><th>ویزیت‌شده</th><th>غایب</th><th>کنسل</th><th>ارزش ثبت‌شده مراجعه</th></tr></thead><tbody>';
  foreach($historical as $r)echo '<tr><td>'.e($r['therapist']).'</td><td>'.fa($r['patients']).'</td><td>'.fa($r['visits']).'</td><td>'.fa($r['done_count']).'</td><td>'.fa($r['absent_count']).'</td><td>'.fa($r['cancelled_count']).'</td><td>'.money($r['charge_total']).'</td></tr>';
  echo '</tbody></table></div></section>';
  $historicalServices=q("SELECT s.name,COUNT(*) uses_count,COUNT(DISTINCT r.pid) patients,SUM(COALESCE(x.amount_toman,0)) amount
      FROM import_event_services x
      JOIN import_patient_events e ON e.record_id=x.record_id AND e.event_no=x.event_no
      JOIN import_records r ON r.id=x.record_id
      JOIN services s ON s.id=x.service_id
      WHERE $historicalWhere
      GROUP BY s.id,s.name ORDER BY uses_count DESC,s.name",$historicalArgs)->fetchAll();
  echo '<section class="panel form-panel"><h2>عملکرد تاریخی خدمات بقراط</h2><div class="table-scroll"><table><thead><tr><th>خدمت مسیحا</th><th>دفعات ثبت</th><th>مراجع یکتا</th><th>جمع مبلغ قابل‌تشخیص</th></tr></thead><tbody>';foreach($historicalServices as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.fa($r['uses_count']).'</td><td>'.fa($r['patients']).'</td><td>'.money($r['amount']).'</td></tr>';echo '</tbody></table></div></section>';
  $sw='s.starts_at>=? AND s.starts_at<DATE_ADD(?,INTERVAL 1 DAY)'.($tid?' AND s.therapist_id='.$tid:'').($clinic?' AND s.clinic_id='.$clinic:'');echo '<section class="panel form-panel"><h2>درآمد خدمات و سهم درمانگران</h2><p class="hint">بر مبنای جلسات انجام‌شده و تعرفه و سهم ثبت‌شده هنگام رزرو. جلسات قدیمی فاقد تعرفه مستقل، مبلغ صفر دارند. این گزارش پرداختِ سهم را تأیید نمی‌کند.</p><div class="table-scroll"><table><thead><tr><th>درمانگر</th><th>جلسات انجام‌شده</th><th>ارزش خدمات</th><th>سهم درمانگر</th><th>سهم کلینیک</th></tr></thead><tbody>';foreach(q("SELECT u.name,COUNT(*) n,SUM(s.price_snapshot) revenue,SUM(s.share_snapshot) share FROM physio_sessions s JOIN staff u ON u.id=s.therapist_id WHERE s.status='done' AND $sw GROUP BY u.id,u.name",$args)->fetchAll() as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.fa($r['n']).'</td><td>'.money($r['revenue']).'</td><td>'.money($r['share']).'</td><td>'.money($r['revenue']-$r['share']).'</td></tr>';echo '</tbody></table></div></section><section class="panel form-panel"><h2>عملکرد خدمات</h2><div class="table-scroll"><table><thead><tr><th>خدمت</th><th>تعداد</th><th>ارزش خدمات انجام‌شده</th></tr></thead><tbody>';foreach(q("SELECT COALESCE(v.name,'ویزیت / خدمت قدیمی') name,COUNT(*) n,SUM(IF(s.status='done',s.price_snapshot,0)) amount FROM physio_sessions s LEFT JOIN services v ON v.id=s.service_id WHERE $sw GROUP BY v.id,v.name",$args)->fetchAll() as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.fa($r['n']).'</td><td>'.money($r['amount']).'</td></tr>';echo '</tbody></table></div><div class="quick-grid">';foreach(q("SELECT s.status,COUNT(*) n FROM physio_sessions s WHERE $sw GROUP BY s.status",$args)->fetchAll() as $r)echo '<div class="summary-box">'.badge($r['status']).'<strong>'.fa($r['n']).'</strong></div>';echo '</div></section><section class="panel form-panel"><h2>گردش روزانه دریافت</h2><div class="table-scroll"><table><thead><tr><th>روز</th><th>خالص دریافتی</th></tr></thead><tbody>';foreach(q("SELECT DATE(x.created_at) day,SUM(x.amount_toman) amount FROM physio_payments x JOIN physio_episodes e ON e.id=x.episode_id WHERE $paywhere GROUP BY DATE(x.created_at) ORDER BY day",$args)->fetchAll() as $r)echo '<tr><td>'.jd($r['day']).'</td><td>'.money($r['amount']).'</td></tr>';echo '</tbody></table></div></section>';}
 if($report||allowed('finance.referral')){echo '<section class="panel form-panel"><h2>سهم‌های معرفی ثبت‌شده</h2>';foreach(q("SELECT r.*,e.fee_toman FROM referral_fees r JOIN physio_episodes e ON e.id=r.episode_id WHERE $where AND r.created_at>=? AND r.created_at<DATE_ADD(?,INTERVAL 1 DAY) ORDER BY r.id DESC",$args)->fetchAll() as $r)echo '<div class="resource-row"><strong>'.e($r['recipient']).'</strong><span>دوره '.fa($r['episode_id']).' · '.money($r['kind']==='percent'?$r['fee_toman']*$r['value']/100:$r['value']).' تومان</span></div>';echo '</section>';}
 if($report){echo '<section class="panel form-panel"><h2>سابقه اصلاحات و ابطال مالی</h2>';foreach(q('SELECT c.*,u.name FROM financial_changes c LEFT JOIN staff u ON u.id=c.actor WHERE c.created_at>=? AND c.created_at<DATE_ADD(?,INTERVAL 1 DAY) ORDER BY c.id DESC',$args)->fetchAll() as $r)echo '<div class="resource-row"><div><strong>تراکنش '.fa($r['payment_id']).' · '.money($r['old_amount']).' ← '.money($r['new_amount']).'</strong><small>'.e($r['reason']).' · '.e($r['name']).' · '.jd($r['created_at']).'</small></div></div>';echo '</section>';}endLayout();}
function dashboardV2():void{need('dashboard');$today=date('Y-m-d');layout('dashboard',user()['role']==='therapist'?'داشبورد درمانگر':'داشبورد مدیریت','برنامه امروز، دسترسی‌های شما و وضعیت کلینیک.');echo '<section class="welcome-banner"><div><span class="welcome-tag">خوش آمدید، '.e(user()['name']).'</span><h2>مراقبت بهتر، با برنامه‌ای روشن</h2><p>'.jd($today,'EEEE، d MMMM yyyy').'</p><div class="banner-actions">';if(allowed('appointments'))echo '<a class="button white" href="/appointment/new">نوبت‌دهی +</a>';if(can('patients'))echo '<a class="button secondary" href="/patients">تمامی مراجعین مجاز</a>';if(can('reports'))echo '<a class="button secondary" href="/reports">گزارش‌های کامل</a>';echo '</div></div></section>';if(can('patients')){echo '<section class="panel form-panel">';liveSearch();echo '</section>';}$rows=can('patients')?sessions('DATE(s.starts_at)=?',[$today],500):[];echo '<div class="stats-grid three"><article class="stat-card"><span>نوبت‌های امروز در دسترس شما</span><strong>'.fa(count($rows)).'</strong></article>';if(can('patients'))echo '<article class="stat-card"><span>مراجعین مجاز</span><strong>'.fa(q('SELECT COUNT(*) FROM patients p WHERE p.active=1 AND '.patientScope())->fetchColumn()).'</strong></article>';if(allowed('finance.history'))echo '<article class="stat-card"><span>خالص دریافتی امروز (تومان)</span><strong>'.money(q('SELECT COALESCE(SUM(amount_toman),0) FROM physio_payments WHERE voided=0 AND DATE(created_at)=?',[$today])->fetchColumn()).'</strong></article>';echo '</div>';if(can('patients')){echo '<section class="panel"><div class="panel-header"><h2>برنامه امروز</h2></div>';sessionTable($rows);echo '</section>';}echo '<div class="quick-grid">';foreach(['staff'=>['همکاران و دسترسی‌ها','/staff'],'services'=>['خدمات و پکیج‌ها','/services'],'inventory'=>['انبار و کالا','/inventory'],'sms'=>['پیامک‌ها و یادآوری‌ها','/sms'],'labels'=>['لیبل‌های مراجعین','/labels'],'forms'=>['فرم‌ها','/forms'],'finance'=>['امور مالی','/finance'],'reports'=>['درآمد و عملکرد','/reports'],'settings'=>['تنظیمات کلینیک','/settings']] as $k=>$v)if(can($k))echo '<a href="'.$v[1].'">'.icon('grid').'<strong>'.$v[0].'</strong></a>';echo '</div>';endLayout();}
function patientExtras($pid,$p):void{if(user()['role']==='admin'){foreach(q('SELECT id FROM import_records WHERE pid=?',[$pid])->fetchAll() as $ir)echo '<a class="button secondary" href="/imports?record='.$ir['id'].'">مشاهده آرشیو منتقل‌شده از بقراط</a>';}echo '<div class="actions" style="margin-bottom:20px">';if(can('forms'))echo '<a class="button secondary" href="/forms?pid='.$pid.'">فرم‌های مراجعه</a>';if(allowed('patients.delete')){formstart('archive_patient');hidden('pid',$pid);echo '<button class="button secondary" data-confirm="پرونده بایگانی شود؟">بایگانی پرونده</button></form>';}echo '</div>';if(allowed('patients.edit')){echo '<details class="panel form-panel"><summary>مسئول پرونده و لیبل</summary>';formstart('patient_assignment');hidden('pid',$pid);echo '<div class="form-grid">';selectfield('providerID','مسئول پرونده',options('staff','active=1 AND deleted=0'),$p['providerID'],'این همکار در محدوده مراجع مرتبط به پرونده دسترسی خواهد داشت.');selectfield('label_id','لیبل',options('labels','active=1 AND deleted=0'),$p['label_id']??0,'لیبل پیشنهادی نوبت‌های این مراجعه.');echo '</div>';formend('ذخیره','/patient?id='.$pid);echo '</details>';}}
