<?php
function adminAction($a):bool{global $db,$config;if(importAction($a))return true;
 if($a==='document_classify'){classifyDocument(num('document_id',1),num('document_type_id'));go('/document-classify?id='.num('document_id',1));}
 if($a==='document_type_save'){documentTypeSave(num('id'),val('name',160,true),isset($_POST['active']));go('/document-types');}
 if($a==='billing_save'){billingSave(num('episode_id',1),num('version'),val('mode',20,true),num('base_toman'),num('discount_id'),num('package_id'),val('reason',1000,true));flash('صورتحساب با حفظ تاریخچه ذخیره شد.');go('/billing?episode='.num('episode_id',1));}
 if($a==='discount_save'){discountCategorySave(num('id'),val('name',160,true),val('kind',10,true),num('value'),isset($_POST['active']));flash('دسته تخفیف ذخیره شد.');go('/billing?episode='.num('episode_id',1));}
 if($a==='history_review'){
  reviewCompletedHistory(num('pid',1),val('source_hash',64,true),val('evidence_hash',64,true),num('version'),val('decision',20,true),num('session_id'),val('reason',1000,true));flash('بررسی با حفظ سابقه ثبت شد.');go('/visit-history?pid='.num('pid',1));
 }
 if($a==='display_save'){
  $data=$_POST['display']??[];if(!is_array($data))throw new DomainException('تنظیمات معتبر نیست.');$policy=val('policy',1)==='1';displaySave($data,$policy,val('role',20),isset($_POST['reset']));flash('تنظیمات نمایش ذخیره شد.');go('/display'.($policy?'?policy=1&role='.val('role',20):''));
 }
 if($a==='appointment_catalog'){
  appointmentCatalogSave(val('kind',20,true),num('id'),val('name',255,true),isset($_POST['active']));flash('فهرست ذخیره شد.');go('/appointment/catalogs');
 }
 if($a==='reception_update'){
  receptionUpdate(num('session_id',1),num('workflow_version'),val('kind',20,true),['selection'=>$_POST['selection']??[],'new_diagnosis'=>val('new_diagnosis',255),'notes'=>val('notes',5000)]);
  flash('اطلاعات مراجعه با ثبت سابقه ذخیره شد.');go('/appointments?'.http_build_query(appointmentFilters($_GET)));
 }
 if($a==='appointment_metadata'){
  $id=num('session_id',1);$input=['visit_type_id'=>num('visit_type_id'),'room'=>val('room',100)];
  if(isset($_POST['package_id']))$input['package_id']=num('package_id');
  foreach(['diagnoses','labels'] as $key)if(isset($_POST['set_'.$key]))$input[$key]=$_POST[$key]??[];
  appointmentMetadata($id,num('workflow_version'),$input);flash('مشخصات مراجعه با ثبت سابقه ذخیره شد.');go('/visit?id='.$id);
 }
 if($a==='permissions'){
  if(user()['role']!=='admin'){http_response_code(403);exit('تعیین دسترسی فقط برای مدیر مجاز است.');}$id=num('id',1);$u=q('SELECT * FROM staff WHERE id=? AND deleted=0',[$id])->fetch();if(!$u||$u['role']==='admin')throw new DomainException('حساب غیرمدیر انتخاب کنید.');$p=defaultsFor('');foreach(permissionGroups() as $g)foreach($g as $key=>$title)$p[$key]=isset($_POST['perm'][str_replace('.','_',$key)]);
  foreach(['profile','contact','forms.visit','forms.general'] as $k){$v=(string)($_POST['scope'][str_replace('.','_',$k)]??'none');if(!in_array($v,str_starts_with($k,'forms.')?['none','own','all']:['none','related','all']))throw new DomainException('محدوده معتبر نیست.');$p[$k]=$v;}
  q('INSERT INTO staff_permissions VALUES(?,?) ON DUPLICATE KEY UPDATE permissions=VALUES(permissions)',[$id,json_encode($p)]);audit('permissions_updated',$id);flash('دسترسی‌ها ذخیره و بلافاصله اعمال شدند.');go('/staff?id='.$id);
 }
 if($a==='staff_delete'){demand('staff.delete');$id=num('id',1);$r=q('SELECT * FROM staff WHERE id=?',[$id])->fetch();if(!$r||$id==user()['id']||($r['role']==='admin'))throw new DomainException('حساب خودتان یا مدیر را نمی‌توانید حذف کنید.');q('UPDATE staff SET active=0,deleted=1 WHERE id=?',[$id]);audit('staff_deleted',$id);flash('حساب حذف و ورود آن مسدود شد؛ سابقه فعالیت حفظ شد.');go('/staff');}
 if($a==='label_save'||$a==='label_delete'){$id=num('id');demand($a==='label_delete'?'labels.delete':($id?'labels.edit':'labels.create'));if($a==='label_delete')q('UPDATE labels SET active=0,deleted=1,is_default=0 WHERE id=?',[$id]);else{$color=val('color',7,true);if(!preg_match('/^#[0-9a-f]{6}$/iD',$color))throw new DomainException('رنگ معتبر انتخاب کنید.');$db->beginTransaction();if(isset($_POST['is_default']))q('UPDATE labels SET is_default=0');$v=[val('name',100,true),$color,isset($_POST['active'])?1:0,isset($_POST['is_default'])?1:0];if($id)q('UPDATE labels SET name=?,color=?,active=?,is_default=? WHERE id=?',[...$v,$id]);else q('INSERT INTO labels(name,color,active,is_default) VALUES(?,?,?,?)',$v);$db->commit();}audit($a,$id);flash('لیبل به‌روز شد.');go('/labels');}
 if($a==='category_save'||$a==='category_delete'){demand('services');$id=num('id');if($a==='category_delete'){if(q('SELECT id FROM services WHERE category_id=? AND deleted=0 LIMIT 1',[$id])->fetchColumn())throw new DomainException('ابتدا خدمات این دسته را به دسته دیگری منتقل کنید.');q('UPDATE service_categories SET deleted=1,active=0 WHERE id=?',[$id]);}elseif($id)q('UPDATE service_categories SET name=?,active=? WHERE id=?',[val('name',160,true),isset($_POST['active'])?1:0,$id]);else q('INSERT INTO service_categories(name,active) VALUES(?,?)',[val('name',160,true),isset($_POST['active'])?1:0]);audit($a,$id);flash('دسته‌بندی ذخیره شد.');go('/services?tab=categories');}
 if($a==='service_save'||$a==='service_delete'){demand('services');$id=num('id');if($a==='service_delete'){if(q('SELECT i.package_id FROM package_items i JOIN packages p ON p.id=i.package_id WHERE i.service_id=? AND p.deleted=0 LIMIT 1',[$id])->fetchColumn())throw new DomainException('ابتدا این خدمت را از پکیج‌ها خارج کنید.');q('UPDATE services SET deleted=1,active=0 WHERE id=?',[$id]);}else{$cat=num('category_id');if($cat&&!q('SELECT id FROM service_categories WHERE id=? AND deleted=0',[$cat])->fetchColumn())throw new DomainException('دسته معتبر انتخاب کنید.');$price=num('price');$v=[val('name',160,true),$price,num('duration',5,480),isset($_POST['active'])?1:0,$cat?:null];if($id)q('UPDATE services SET name=?,price=?,duration=?,active=?,category_id=? WHERE id=?',[...$v,$id]);else{q('INSERT INTO services(name,price,duration,active,category_id) VALUES(?,?,?,?,?)',$v);$id=(int)$db->lastInsertId();}syncServiceBaseTariff($id,$price,(int)user()['id']);refreshServiceCurrentPrice($id);}audit($a,$id);flash('خدمت ذخیره شد.');go('/services');}
 if($a==='tariff_save'||$a==='tariff_delete'){demand('services');$id=num('tariff_id')?:num('id');if($a==='tariff_delete'){$row=q('SELECT * FROM service_tariffs WHERE id=? AND deleted=0',[$id])->fetch();if(!$row)throw new DomainException('تعرفه پیدا نشد.');q('UPDATE service_tariffs SET deleted=1,active=0 WHERE id=?',[$id]);refreshServiceCurrentPrice((int)$row['service_id']);audit($a,$id);flash('تعرفه بایگانی شد.');go('/services?tab=tariffs');}$sid=num('service_id',1);if(!q('SELECT id FROM services WHERE id=? AND deleted=0',[$sid])->fetchColumn())throw new DomainException('خدمت معتبر انتخاب کنید.');$type=val('tariff_type',20,true);if(!in_array($type,['normal','contract'],true))throw new DomainException('نوع تعرفه معتبر نیست.');$contract=val('contract_name',160);if($type==='contract'&&$contract==='')throw new DomainException('برای تعرفه قراردادی نام قرارداد را وارد کنید.');if($type==='normal')$contract='';$title=val('title',160,true);$price=num('price_toman');$from=datevalue('effective_from',true);$to=datevalue('effective_to');if($to&&$to<$from)throw new DomainException('تاریخ پایان تعرفه نمی‌تواند قبل از تاریخ شروع باشد.');$active=isset($_POST['active'])?1:0;$v=[$sid,$type,$title,$contract,$price,$from,$to,$active,(int)user()['id']];if($id){if(!q('SELECT id FROM service_tariffs WHERE id=? AND deleted=0',[$id])->fetchColumn())throw new DomainException('تعرفه پیدا نشد.');q("UPDATE service_tariffs SET service_id=?,tariff_type=?,title=?,contract_name=?,price_toman=?,effective_from=?,effective_to=?,active=?,source_system='masiha',created_by=? WHERE id=?",[...$v,$id]);}else{q("INSERT INTO service_tariffs(service_id,tariff_type,title,contract_name,price_toman,effective_from,effective_to,active,source_system,created_by) VALUES(?,?,?,?,?,?,?,?,'masiha',?)",$v);$id=(int)$db->lastInsertId();}refreshServiceCurrentPrice($sid);audit($a,$id);flash('تعرفه ذخیره شد.');go('/services?tab=tariffs&tariff_id='.$id);}
 if($a==='share_save'||$a==='share_delete'){demand('services');$sid=num('service_id',1);$tid=num('staff_id',1);if(!q('SELECT id FROM services WHERE id=? AND deleted=0',[$sid])->fetchColumn()||!q('SELECT id FROM staff WHERE id=? AND active=1 AND deleted=0',[$tid])->fetchColumn())throw new DomainException('خدمت و همکار معتبر انتخاب کنید.');if($a==='share_delete')q('DELETE FROM service_staff WHERE service_id=? AND staff_id=?',[$sid,$tid]);else{$kind=val('share_type',10);if(!in_array($kind,['fixed','percent']))throw new DomainException('نوع سهم معتبر نیست.');$value=decimalValue('share_value',$kind==='percent'?100:999999999);q('INSERT INTO service_staff VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE share_type=VALUES(share_type),share_value=VALUES(share_value)',[$sid,$tid,$kind,$value]);}audit($a,$sid);flash('خدمت و سهم همکار ذخیره شد.');go('/services?tab=shares&id='.$sid);}
 if($a==='package_save'||$a==='package_delete'){demand('services');$id=num('id');if($a==='package_delete')q('UPDATE packages SET deleted=1,active=0 WHERE id=?',[$id]);else{$items=$_POST['qty']??[];if(!is_array($items))throw new DomainException('اقلام معتبر نیست.');$chosen=[];$total=0;foreach($items as $sid=>$qty){$qty=MasihaOtp::digits((string)$qty);if(!ctype_digit($qty)||(int)$qty>365)throw new DomainException('تعداد خدمت از صفر تا ۳۶۵ است.');if(!(int)$qty)continue;$r=q('SELECT * FROM services WHERE id=? AND deleted=0',[(int)$sid])->fetch();if(!$r)throw new DomainException('خدمت معتبر نیست.');$chosen[(int)$sid]=(int)$qty;$total+=(int)$r['price']*(int)$qty;}if(!$chosen)throw new DomainException('حداقل یک خدمت انتخاب کنید.');$auto=isset($_POST['auto_price']);$price=$auto?$total:num('price');$db->beginTransaction();$v=[val('name',160,true),$price,$auto?1:0,isset($_POST['active'])?1:0];if($id){q('UPDATE packages SET name=?,price=?,auto_price=?,active=? WHERE id=?',[...$v,$id]);q('DELETE FROM package_items WHERE package_id=?',[$id]);}else{q('INSERT INTO packages(name,price,auto_price,active) VALUES(?,?,?,?)',$v);$id=(int)$db->lastInsertId();}foreach($chosen as $sid=>$qty)q('INSERT INTO package_items VALUES(?,?,?)',[$id,$sid,$qty]);$db->commit();}audit($a,$id);flash('پکیج ذخیره شد.');go('/services?tab=packages');}
 if($a==='work_schedule_save'||$a==='work_schedule_delete'){
  demand('appointments');$id=isset($_POST['id'])?num('id'):0;if($a==='work_schedule_delete')disableScheduleRecord('schedule',$id);
  else saveTherapistSchedule(['therapist_id'=>num('therapist_id',1),'clinic_id'=>num('clinic_id'),'weekday'=>num('weekday',0,6),'start_time'=>val('start_time',5,true).':00','end_time'=>val('end_time',5,true).':00','effective_from'=>datevalue('effective_from'),'effective_to'=>datevalue('effective_to')],$id);
  flash('برنامه حضور ذخیره شد.');go('/availability');
 }
 if($a==='work_schedule_copy_days'){
  demand('appointments');$days=$_POST['target_days']??[];if(!is_array($days))throw new DomainException('روزهای مقصد معتبر نیست.');$n=copyTherapistScheduleDays(num('therapist_id',1),num('source_weekday',0,6),$days);flash('برنامه به روزهای انتخاب‌شده کپی شد: '.fa($n).' بازه جدید.');go('/availability');
 }
 if($a==='work_schedule_copy'){
  demand('appointments');$n=copyTherapistSchedule(num('source_therapist_id',1),num('target_therapist_id',1));flash('برنامه حضور کپی شد: '.fa($n).' بازه جدید.');go('/availability');
 }
 if($a==='sms_config'){demand('sms');global $config;$cfg=MasihaSms::config();$sender=val('sms_sender',30);if($sender!==''&&!preg_match('/^[0-9]{3,30}$/D',MasihaOtp::digits($sender)))throw new DomainException('شماره فرستنده پیامک معتبر نیست.');$cfg['sender']=$sender===''?'':MasihaOtp::digits($sender);if(isset($_POST['sms_notifications'])&&empty($cfg['key']))throw new DomainException('ابتدا کلید کاوه‌نگار را در تنظیمات کلینیک ثبت کنید.');$file=$config['storage'].'/sms.json';$tmp=$file.'.tmp';if(file_put_contents($tmp,json_encode($cfg,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR))===false)throw new RuntimeException('sms_config');chmod($tmp,0600);rename($tmp,$file);setsetting('sms_notifications',isset($_POST['sms_notifications'])?'1':'0');audit('sms_config');flash('تنظیمات پیامک ذخیره شد.');go('/sms');}
 if($a==='sms_template_save'){demand('sms');$key=val('event_key',50,true);$row=q('SELECT id FROM sms_templates WHERE event_key=?',[$key])->fetch();if(!$row)throw new DomainException('قالب پیامک پیدا نشد.');$body=val('message_template',2000,true);$offset=num('send_offset_minutes',0,10080);if($key!=='appointment_reminder')$offset=0;q('UPDATE sms_templates SET enabled=?,message_template=?,send_offset_minutes=? WHERE event_key=?',[isset($_POST['enabled'])?1:0,$body,$offset,$key]);audit('sms_template_save',(int)$row['id']);flash('قالب پیامک ذخیره شد.');go('/sms#templates');}
 if($a==='sms_campaign_queue'){demand('sms');go('/sms/audience');}
 if($a==='audience_preview'){$id=audiencePreview($_POST,val('title',160,true),val('message',1000,true));go('/sms/audience?preview='.$id);}
 if($a==='audience_queue'){audienceQueue(val('preview_id',32,true));flash('مخاطبان تأییدشده در صف قرار گرفتند.');go('/sms');}
 if($a==='sms_retry'||$a==='sms_cancel'){demand('sms');$id=num('id',1);$row=q('SELECT status,pid FROM sms_outbox WHERE id=?',[$id])->fetch();if(!$row||!patientAllowed((int)$row['pid'])||!patientAllowed((int)$row['pid'],'contact'))throw new DomainException('به این پیام دسترسی ندارید.');if($a==='sms_retry'){if(!in_array($row['status'],['failed','cancelled'],true))throw new DomainException('فقط پیام ناموفق یا لغوشده قابل تلاش مجدد است.');q("UPDATE sms_outbox SET status='queued',scheduled_at=NOW(),last_error='' WHERE id=?",[$id]);}else{if(!in_array($row['status'],['queued','failed'],true))throw new DomainException('این پیام قابل لغو نیست.');q("UPDATE sms_outbox SET status='cancelled' WHERE id=?",[$id]);}audit($a,$id);flash($a==='sms_retry'?'پیام دوباره در صف قرار گرفت.':'پیام لغو شد.');go('/sms');}
 if($a==='sms_process'){demand('sms');$result=MasihaSms::process(20);if(!empty($result['disabled']))throw new DomainException('ارسال پیامک غیرفعال است.');audit('sms_process');flash('پردازش صف: '.fa($result['sent']).' ارسال، '.fa($result['failed']).' ناموفق.');go('/sms');}
 if($a==='visit_reverse'){
  demand('appointments.reverse');$id=num('session_id',1);workflowReverse($id,num('workflow_version'),val('reason',1000,true));flash('مرحله با حفظ سابقه و ثبت دلیل اصلاح شد.');go('/visit?id='.$id);
 }
 if($a==='turn_state'||$a==='visit_state'){
  demand('appointments');$id=num('session_id',1);
  $target=$a==='visit_state'?val('state',20,true):match(val('turn_state',20,true)){'none'=>'scheduled','waiting'=>'waiting','called'=>'referred','in_service'=>'in_service','done'=>'discharged',default=>throw new DomainException('وضعیت صف معتبر نیست.')};
  $expected=isset($_POST['workflow_version'])?num('workflow_version'):null;
  workflowTransition($id,$target,['reason'=>val('reason',1000)],$expected);
  if(in_array($target,['absent','cancelled','discharged'],true))MasihaSms::safely(fn()=>MasihaSms::cancelSession($id));
  flash('مرحله مراجعه با ثبت سابقه به‌روز شد.');if(($_POST['return_appointments']??'')==='1')go('/appointments?'.http_build_query(appointmentFilters($_GET)));if(($_POST['return_visit']??'')==='1')go('/visit?id='.$id);$clinic=num('clinic_id');go('/turn-board'.($clinic?'?clinic='.$clinic:''));
 }
 if($a==='absence_save'||$a==='absence_delete'){
  demand('appointments');if($a==='absence_delete')disableScheduleRecord('absence',num('id',1));
  else { $parse=static function($key){$v=val($key,16,true);$d=DateTimeImmutable::createFromFormat('!Y-m-d\\TH:i',$v);if(!$d||$d->format('Y-m-d\\TH:i')!==$v)throw new DomainException('تاریخ و ساعت غیبت معتبر نیست.');return $d->format('Y-m-d H:i:s');};saveTherapistAbsence(num('therapist_id',1),$parse('absence_from'),$parse('absence_to'),val('reason',500));}
  flash('برنامه غیبت ذخیره شد.');go('/availability');
 }
 if($a==='clinic_save'){demand('settings');$id=num('id');$v=[val('name',160,true),val('address',2000),val('phone',30),isset($_POST['active'])?1:0];if($id)q('UPDATE clinics SET name=?,address=?,phone=?,active=? WHERE id=?',[...$v,$id]);else q('INSERT INTO clinics(name,address,phone,active) VALUES(?,?,?,?)',$v);audit($a,$id);flash('کلینیک ثبت شد.');go('/appearance');}
 if($a==='appearance') {
  demand('settings');$values=[];
  foreach(['theme_color','theme_hover_color','theme_background_color'] as $key){
   $color=val($key,7,true);
   if(!preg_match('/^#[0-9a-f]{6}$/iD',$color))throw new DomainException('رنگ معتبر انتخاب کنید.');
   $values[$key]=strtolower($color);
  }
  foreach(['font_id','heading_font_id'] as $key){
   $font=num($key);
   if($font&&!q('SELECT id FROM custom_fonts WHERE id=?',[$font])->fetchColumn())throw new DomainException('فونت معتبر نیست.');
   $values[$key]=$font;
  }
  $db->beginTransaction();
  try{foreach($values as $k=>$v)setsetting($k,$v);audit($a);$db->commit();}
  catch(Throwable $ex){if($db->inTransaction())$db->rollBack();throw $ex;}
  flash('رنگ‌ها و فونت‌های جدید برای همه صفحات ذخیره شد.');go('/appearance');
 }
 if($a==='font_upload'){demand('settings');$f=$_FILES['font']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK||$f['size']>3*1024*1024||!is_uploaded_file($f['tmp_name']))throw new DomainException('فایل فونت تا ۳ مگابایت انتخاب کنید.');$signature=file_get_contents($f['tmp_name'],false,null,0,4);$format=match($signature){'wOFF'=>'woff','wOF2'=>'woff2',default=>null};if(!$format)throw new DomainException('فقط فونت WOFF یا WOFF2 پذیرفته می‌شود.');$filename=bin2hex(random_bytes(20)).'.'.$format;if(!is_dir($config['storage'].'/fonts'))mkdir($config['storage'].'/fonts',0700);if(!move_uploaded_file($f['tmp_name'],$config['storage'].'/fonts/'.$filename))throw new RuntimeException('font');chmod($config['storage'].'/fonts/'.$filename,0600);q('INSERT INTO custom_fonts(name,filename,format) VALUES(?,?,?)',[val('name',100,true),$filename,$format]);audit($a);flash('فونت بارگذاری شد؛ آن را از فهرست ظاهر انتخاب کنید.');go('/appearance');}
 if($a==='form_save'||$a==='form_delete'){$id=num('id');$old=$id?q('SELECT * FROM clinic_forms WHERE id=? AND deleted=0',[$id])->fetch():null;$pid=$old?(int)$old['pid']:num('pid',1);requirePatient($pid);$kind=$old?$old['kind']:val('kind',10);if(!in_array($kind,['visit','general'])||scope('forms.'.$kind)==='none'||($old&&scope('forms.'.$kind)==='own'&&(int)$old['created_by']!==(int)user()['id'])){http_response_code(403);exit('به این فرم دسترسی ندارید.');}if($a==='form_delete')q('UPDATE clinic_forms SET deleted=1 WHERE id=?',[$id]);elseif($id)q('UPDATE clinic_forms SET title=?,body=? WHERE id=?',[val('title',160,true),val('body',20000,true),$id]);else q('INSERT INTO clinic_forms(pid,title,kind,body,created_by) VALUES(?,?,?,?,?)',[$pid,val('title',160,true),$kind,val('body',20000,true),user()['id']]);audit($a,$id);flash('فرم ذخیره شد.');go('/forms?pid='.$pid);}
 if($a==='patient_assignment'){demand('patients.edit');$pid=num('pid',1);requirePatient($pid);$tid=num('providerID');if($tid&&!q('SELECT id FROM staff WHERE id=? AND active=1 AND deleted=0',[$tid])->fetchColumn())throw new DomainException('همکار معتبر انتخاب کنید.');$label=num('label_id');if($label&&!q('SELECT id FROM labels WHERE id=? AND deleted=0 AND active=1',[$label])->fetchColumn())throw new DomainException('لیبل معتبر انتخاب کنید.');q('UPDATE patients SET providerID=?,label_id=? WHERE pid=?',[$tid,$label?:null,$pid]);audit($a,$pid);flash('مسئول پرونده و لیبل ذخیره شد.');go('/patient?id='.$pid);}
 if($a==='book_v2'){demand('appointments');$pid=num('pid',1);requirePatient($pid);if(!q('SELECT pid FROM patients WHERE pid=? AND active=1',[$pid])->fetchColumn())throw new DomainException('بیمار فعال انتخاب کنید.');$tid=num('therapist_id',1);if(!q("SELECT id FROM staff WHERE id=? AND active=1 AND deleted=0 AND role IN ('therapist','admin')",[$tid])->fetchColumn())throw new DomainException('درمانگر فعال انتخاب کنید.');$date=datevalue('date',true);$time=val('time',5,true);if(!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/D',$time))throw new DomainException('ساعت معتبر نیست.');$start=$date.' '.$time.':00';$end=date('Y-m-d H:i:s',strtotime($start)+num('duration',5,480)*60);$clinic=num('clinic_id',1);if(!q('SELECT id FROM clinics WHERE id=? AND active=1',[$clinic])->fetchColumn())throw new DomainException('کلینیک فعال انتخاب کنید.');$label=num('label_id');if(!$label)$label=(int)q('SELECT label_id FROM patients WHERE pid=?',[$pid])->fetchColumn()?:((int)q('SELECT id FROM labels WHERE is_default=1 AND active=1 AND deleted=0 LIMIT 1')->fetchColumn());if($label&&!q('SELECT id FROM labels WHERE id=? AND active=1 AND deleted=0',[$label])->fetchColumn())$label=0;
 $visitType=isset($_POST['visit_type_id'])?num('visit_type_id'):0;if($visitType&&!q('SELECT id FROM visit_types WHERE id=? AND active=1',[$visitType])->fetchColumn())throw new DomainException('نوع ویزیت فعال انتخاب کنید.');
 $sid=num('service_id');$service=$sid?q('SELECT * FROM services WHERE id=? AND active=1 AND deleted=0',[$sid])->fetch():null;if($sid&&!$service)throw new DomainException('خدمت فعال انتخاب کنید.');$share=$sid?q('SELECT * FROM service_staff WHERE service_id=? AND staff_id=?',[$sid,$tid])->fetch():null;if($sid&&!$share)throw new DomainException('این خدمت برای درمانگر انتخاب‌شده تعریف نشده است.');$tariffId=num('tariff_id');$tariff=null;if($tariffId){if(!$sid)throw new DomainException('تعرفه بدون خدمت قابل انتخاب نیست.');$tariff=q("SELECT * FROM service_tariffs WHERE id=? AND service_id=? AND active=1 AND deleted=0 AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)",[$tariffId,$sid,$date,$date])->fetch();if(!$tariff)throw new DomainException('تعرفه برای خدمت و تاریخ انتخاب‌شده معتبر نیست.');}$price=$tariff?(int)$tariff['price_toman']:($service?(int)$service['price']:0);$tariffTitle=$tariff?trim(($tariff['tariff_type']==='contract'&&$tariff['contract_name']!==''?$tariff['contract_name'].' · ':'').$tariff['title']):'';$shareValue=$share?($share['share_type']==='percent'?$price*$share['share_value']/100:min($price,$share['share_value'])):0;
 $room=val('room',100);$equipment=val('equipment',100);validateResources($room,$equipment);$issue=therapistAvailabilityIssue($start,$end,$tid,$clinic);if($issue)throw new DomainException($issue);$epid=num('episode_id');$notes=val('notes',5000);$sessionId=0;$actor=(int)user()['id'];schedulingLock();try{$db->beginTransaction();if($issue=therapistAvailabilityIssue($start,$end,$tid,$clinic))throw new DomainException($issue);if(conflict($start,$end,$tid,$room,$equipment,$pid))throw new DomainException('زمان انتخابی با نوبت بیمار، درمانگر یا منابع تداخل دارد.');if($epid){$ep=q('SELECT * FROM physio_episodes WHERE id=? AND pid=? AND status=\'active\' FOR UPDATE',[$epid,$pid])->fetch();if(!$ep)throw new DomainException('دوره فعال این بیمار را انتخاب کنید.');if((int)q("SELECT COUNT(*) FROM physio_sessions WHERE episode_id=? AND status IN ('scheduled','done')",[$epid])->fetchColumn()>=(int)$ep['planned_sessions'])throw new DomainException('ظرفیت دوره تکمیل است.');}else{q("INSERT INTO physio_episodes(pid,diagnosis,body_region,assessment,goals,precautions,exercises,planned_sessions,fee_toman,created_by) VALUES(?,?,'عمومی','','','','',1,?,?)",[$pid,$service['name']??'ویزیت فیزیوتراپی',$price,$actor]);$epid=(int)$db->lastInsertId();}q('INSERT INTO physio_sessions(episode_id,therapist_id,starts_at,ends_at,room,equipment,treatment,notes,created_by,label_id,clinic_id,service_id,tariff_id,tariff_title_snapshot,price_snapshot,share_snapshot,visit_type_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$epid,$tid,$start,$end,$room,$equipment,$service['name']??'ویزیت فیزیوتراپی',$notes,$actor,$label?:null,$clinic,$sid?:null,$tariffId?:null,$tariffTitle,$price,$shareValue,$visitType?:null]);$sessionId=(int)$db->lastInsertId();q('UPDATE physio_sessions SET reception_notes=? WHERE id=?',[$notes,$sessionId]);workflowBooked($sessionId,'staff');audit('appointment_created',$sessionId);$db->commit();}catch(Throwable $ex){if($db->inTransaction())$db->rollBack();throw $ex;}finally{schedulingUnlock();}if($sessionId)MasihaSms::safely(fn()=>MasihaSms::queueAppointment($sessionId,$actor));flash('نوبت ثبت شد.');go('/appointments?date='.$date);
 }
 if($a==='payment_edit'||$a==='payment_void'){demand($a==='payment_void'?'finance.delete':'finance.edit');$id=num('id',1);$reason=val('reason',255,true);$db->beginTransaction();$p=q('SELECT * FROM physio_payments WHERE id=? FOR UPDATE',[$id])->fetch();if(!$p||$p['voided'])throw new DomainException('تراکنش فعال پیدا نشد.');q('SELECT id FROM physio_episodes WHERE id=? FOR UPDATE',[$p['episode_id']]);$new=$a==='payment_void'?0:num('amount_toman',-999999999999);if($a!=='payment_void'&&!$new)throw new DomainException('مبلغ صفر مجاز نیست.');if(totalpaid($p['episode_id'])-$p['amount_toman']+$new<0)throw new DomainException('مانده دریافتی نمی‌تواند منفی شود.');q('INSERT INTO financial_changes(payment_id,old_amount,new_amount,reason,actor) VALUES(?,?,?,?,?)',[$id,$p['amount_toman'],$new,$reason,user()['id']]);if($a==='payment_void')q('UPDATE physio_payments SET voided=1,change_reason=? WHERE id=?',[$reason,$id]);else q('UPDATE physio_payments SET amount_toman=?,change_reason=? WHERE id=?',[$new,$reason,$id]);billingAudit('payment',$id,$a,$reason,$p,q('SELECT * FROM physio_payments WHERE id=?',[$id])->fetch());audit($a,$id);$db->commit();flash('اصلاح مالی با حفظ سابقه ثبت شد.');go('/finance');}
 if($a==='fee_edit'){demand('finance.edit');go('/billing?episode='.num('episode_id',1));}
 if($a==='referral_save'){demand('finance.referral');$id=num('episode_id',1);if(!q('SELECT id FROM physio_episodes WHERE id=?',[$id])->fetchColumn())throw new DomainException('دوره پیدا نشد.');$kind=val('kind',10);if(!in_array($kind,['fixed','percent']))throw new DomainException('نوع معتبر نیست.');q('INSERT INTO referral_fees(episode_id,recipient,kind,value,created_by) VALUES(?,?,?,?,?)',[$id,val('recipient',160,true),$kind,decimalValue('value',$kind==='percent'?100:999999999),user()['id']]);audit($a,$id);flash('سهم معرفی ثبت شد.');go('/finance');}
 if($a==='inventory_item_save'){demand('inventory');$id=num('id');$name=val('name',255,true);$unit=val('unit',40,true);$price=num('sale_price_toman');$active=isset($_POST['active'])?1:0;if($id){if(!q('SELECT id FROM inventory_items WHERE id=?',[$id])->fetchColumn())throw new DomainException('کالا پیدا نشد.');q('UPDATE inventory_items SET name=?,unit=?,sale_price_toman=?,active=? WHERE id=?',[$name,$unit,$price,$active,$id]);}else{q('INSERT INTO inventory_items(name,unit,sale_price_toman,active) VALUES(?,?,?,?)',[$name,$unit,$price,$active]);$id=(int)$db->lastInsertId();}audit('inventory_item_save',$id);flash('کالا ذخیره شد.');go('/inventory?id='.$id);}
 if($a==='inventory_opening'){stockOpening(num('item_id',1),val('opening_quantity',30,true),datevalue('opening_as_of',true));flash('موجودی شروع ثبت شد.');go('/inventory?id='.num('item_id',1));}
 if($a==='inventory_adjust'){stockMove(num('item_id',1),val('quantity_delta',30,true),datevalue('occurred_on',true),val('note',500,true),val('request_key',32,true));flash('تعدیل ثبت شد.');go('/inventory?id='.num('item_id',1));}
 if($a==='stock_consume'){stockMove(num('item_id',1),stockDecimal(-abs(stockUnits(val('quantity',30,true)))),date('Y-m-d'),val('note',500,true),val('request_key',32,true),num('session_id',1));flash('مصرف ثبت شد.');go('/visit?id='.num('session_id',1));}
 if($a==='stock_return'){demand('inventory');$m=q('SELECT * FROM inventory_movements WHERE id=?',[num('movement_id',1)])->fetch();if(!$m)throw new DomainException('حرکت پیدا نشد.');stockMove((int)$m['item_id'],stockDecimal(-stockUnits($m['quantity_delta'])),date('Y-m-d'),val('note',500,true),val('request_key',32,true),num('session_id',1),(int)$m['id']);flash('برگشت ثبت شد.');go('/visit?id='.num('session_id',1));}
 if($a==='legacy_balance_payment'){demand('finance.pay');$pid=num('pid',1);if(!q('SELECT pid FROM patients WHERE pid=? AND active=1',[$pid])->fetchColumn())throw new DomainException('بیمار پیدا نشد.');$amount=num('amount_toman',1,999999999999);$balance=(int)q('SELECT COALESCE(SUM(debit_toman-credit_toman),0) FROM patient_account_ledger WHERE pid=? AND voided=0',[$pid])->fetchColumn();if($balance<=0)throw new DomainException('مانده بدهی قبلی برای این بیمار وجود ندارد.');if($amount>$balance)throw new DomainException('مبلغ پرداخت از مانده بدهی قبلی بیشتر است.');$reference=val('reference',255);q("INSERT INTO patient_account_ledger(pid,entry_date,entry_type,debit_toman,credit_toman,reference,source_system,source_record_id,entry_key,created_by,voided) VALUES(?,CURDATE(),'payment',0,?,?, 'masiha',NULL,NULL,?,0)",[$pid,$amount,$reference,user()['id']]);audit('legacy_balance_payment',$pid);flash('پرداخت مانده قبلی ثبت شد.');go('/finance?legacy_patient='.$pid);}
 return false;
}
function refreshServiceCurrentPrice(int $serviceId):void{
 $price=q("SELECT price_toman FROM service_tariffs WHERE service_id=? AND tariff_type='normal' AND active=1 AND deleted=0 AND effective_from<=CURDATE() AND (effective_to IS NULL OR effective_to>=CURDATE()) ORDER BY effective_from DESC,id DESC LIMIT 1",[$serviceId])->fetchColumn();
 if($price!==false)q('UPDATE services SET price=? WHERE id=?',[(int)$price,$serviceId]);
 q('UPDATE packages p SET price=(SELECT COALESCE(SUM(s.price*i.quantity),0) FROM package_items i JOIN services s ON s.id=i.service_id WHERE i.package_id=p.id) WHERE auto_price=1');
}
function syncServiceBaseTariff(int $serviceId,int $price,int $actor):void{
 $today=date('Y-m-d');$id=(int)(q("SELECT id FROM service_tariffs WHERE service_id=? AND tariff_type='normal' AND source_system='masiha' AND effective_from=? AND deleted=0 ORDER BY id DESC LIMIT 1",[$serviceId,$today])->fetchColumn()?:0);
 if($id)q("UPDATE service_tariffs SET title='تعرفه عادی',contract_name='',price_toman=?,active=1,effective_to=NULL,created_by=? WHERE id=?",[$price,$actor,$id]);
 else q("INSERT INTO service_tariffs(service_id,tariff_type,title,contract_name,price_toman,effective_from,effective_to,active,source_system,created_by) VALUES(?,'normal','تعرفه عادی','',?,?,NULL,1,'masiha',?)",[$serviceId,$price,$today,$actor]);
}
function decimalValue($key,$max):float{$v=MasihaOtp::digits(val($key,20,true));if(!preg_match('/^\d+(\.\d{1,2})?$/D',$v)||(float)$v>$max)throw new DomainException('مقدار عددی معتبر وارد کنید.');return (float)$v;}
function quantityValue($key,$max):float{$v=MasihaOtp::digits(val($key,20,true));if(!preg_match('/^\d+(\.\d{1,3})?$/D',$v)||(float)$v>$max)throw new DomainException('مقدار عددی معتبر وارد کنید.');return (float)$v;}
function signedDecimalValue($key,$max):float{$v=MasihaOtp::digits(val($key,20,true));if(!preg_match('/^-?\d+(\.\d{1,3})?$/D',$v)||abs((float)$v)>$max)throw new DomainException('مقدار عددی معتبر وارد کنید.');return (float)$v;}
