<?php
function adminApi($path):void{global $config;
 if($path==='/theme.css'){header('Content-Type: text/css');$color=setting('theme_color','#087f75');if(!preg_match('/^#[0-9a-f]{6}$/iD',$color))$color='#087f75';echo ':root{--teal:'.$color.';--primary:'.$color.'} .button.primary,.brand-initial{background:'.$color.'} .welcome-banner{background:linear-gradient(120deg,'.$color.',#183e49)}';foreach(['font_id'=>'body,input,select,textarea,button','heading_font_id'=>'h1,h2,h3,.brand'] as $key=>$selector){$id=(int)setting($key,'0');if($id&&q('SELECT id FROM custom_fonts WHERE id=?',[$id])->fetchColumn())echo "@font-face{font-family:custom$id;src:url('/font?id=$id')} $selector{font-family:custom$id,Vazir,sans-serif}";}exit;}
 if($path==='/font'){$r=q('SELECT * FROM custom_fonts WHERE id=?',[(int)($_GET['id']??0)])->fetch();if(!$r){http_response_code(404);exit;}$f=$config['storage'].'/fonts/'.basename($r['filename']);if(!is_file($f)){http_response_code(404);exit;}header('Content-Type: font/'.$r['format']);readfile($f);exit;}
 if(!str_starts_with($path,'/api/'))return;if(!user()){http_response_code(401);exit;}header('Content-Type: application/json; charset=utf-8');
 if($path==='/api/patients'){need('patients');$term=mb_substr(MasihaOtp::digits(trim((string)($_GET['q']??''))),0,100);$where='p.active=1 AND '.patientScope();$args=[];if($term!==''){$where.=' AND (CONCAT(p.fname,\' \',p.lname) LIKE ? OR p.national_id LIKE ? OR ('.patientScope('p','contact').' AND p.phone_cell LIKE ?))';$args=array_fill(0,3,'%'.$term.'%');}$rows=q('SELECT p.pid,p.fname,p.lname,p.phone_cell,p.national_id FROM patients p WHERE '.$where.' ORDER BY p.lname LIMIT 15',$args)->fetchAll();$out=[];foreach($rows as $r)$out[]=['id'=>$r['pid'],'name'=>patientName($r),'phone'=>patientAllowed($r['pid'],'contact')?$r['phone_cell']:null,'national_id'=>$r['national_id']];echo json_encode($out,JSON_UNESCAPED_UNICODE);exit;}
 if($path==='/api/booking'){need('appointments');$tid=(int)($_GET['therapist']??0);$pid=(int)($_GET['pid']??0);$eps=[];if($pid){requirePatient($pid);$eps=q("SELECT id,diagnosis FROM physio_episodes WHERE pid=? AND status='active' ORDER BY id DESC",[$pid])->fetchAll();}$services=q('SELECT s.id,s.name,s.duration FROM services s JOIN service_staff x ON x.service_id=s.id WHERE x.staff_id=? AND s.active=1 AND s.deleted=0 ORDER BY s.name',[$tid])->fetchAll();echo json_encode(['services'=>$services,'episodes'=>$eps],JSON_UNESCAPED_UNICODE);exit;}
 http_response_code(404);echo '{}';exit;
}
function guardPage($path):void{
 if(in_array($path,['/patient','/patients/edit'])){$pid=(int)($_GET['id']??0);requirePatient($pid);if($path==='/patients/edit'){demand('patients.edit');if(!patientAllowed($pid,'contact')){http_response_code(403);exit('برای ویرایش مشخصات کامل، دسترسی تماس لازم است.');}}}
 if($path==='/patients/new')demand('patients.create');
 if($path==='/session'){$id=(int)($_GET['id']??0);$s=q('SELECT s.*,e.pid FROM physio_sessions s JOIN physio_episodes e ON e.id=s.episode_id WHERE s.id=?',[$id])->fetch();if(!$s){http_response_code(404);exit;}requirePatient($s['pid']);if(scope('forms.visit')==='none'||(scope('forms.visit')==='own'&&(int)$s['created_by']!==(int)user()['id'])){http_response_code(403);exit('به این فرم دسترسی ندارید.');}}
}
