<?php
function clinicalReportData(array $input):array{
 if(!allowed('reports.clinical'))throw new DomainException('اجازه گزارش عملکرد ندارید.');$f=appointmentFilters($input);if(user()['role']==='therapist')$f['therapist']=(int)user()['id'];[$where,$a]=appointmentWhere($f);
 $rows=q("SELECT DATE(s.starts_at) day,COUNT(*) appointments,COUNT(DISTINCT p.pid) patients,SUM(s.status='done') completed,SUM(s.status='absent') absent,SUM(s.status='cancelled') cancelled,SUM(w.arrived_at IS NOT NULL) arrived".appointmentJoins()."WHERE $where GROUP BY DATE(s.starts_at) ORDER BY day",$a)->fetchAll();return compact('f','rows');
}
function clinicalReportView():void{demand('reports.clinical');try{$data=clinicalReportData($_GET);}catch(DomainException $e){layout('reports','گزارش عملکرد');echo '<p class="notice">'.e($e->getMessage()).'</p>';endLayout();return;}layout('reports','گزارش روزانه و بازه‌ای','تعداد مراجعه و تکمیل جلسات بومی؛ سوابق وارداتی جداگانه تطبیق داده می‌شوند.');echo '<section class="panel form-panel"><form method="get"><div class="form-grid">';field('from','از',$data['f']['from'],'date');field('to','تا',$data['f']['to'],'date');if(user()['role']!=='therapist')selectfield('therapist','درمانگر',['0'=>'همه']+array_filter(therapists()),$data['f']['therapist']);selectfield('clinic','کلینیک',['0'=>'همه']+options('clinics'),$data['f']['clinic']);echo '</div><button class="button primary">نمایش</button></form></section><section class="panel"><div class="table-scroll"><table><thead><tr><th>روز</th><th>نوبت</th><th>بیمار یکتا در روز</th><th>انجام‌شده</th><th>غیبت</th><th>کنسلی</th><th>ورود ثبت‌شده</th></tr></thead><tbody>';foreach($data['rows'] as $r){echo '<tr><td>'.jd($r['day']).'</td>';foreach(['appointments','patients','completed','absent','cancelled','arrived'] as $k)echo '<td>'.fa($r[$k]).'</td>';echo '</tr>';}echo '</tbody></table></div></section>';endLayout();}
function progressData(int $pid,int $page=1):array{
 if(!user()||!patientAllowed($pid)||scope('forms.visit')==='none')throw new DomainException('اجازه مشاهده روند درمان ندارید.');$where='ep.pid=?';$a=[$pid];if(scope('forms.visit')!=='all'){$where.=' AND (s.therapist_id=? OR s.created_by=?)';$a[]=user()['id'];$a[]=user()['id'];}
 $join=' FROM physio_sessions s JOIN physio_episodes ep ON ep.id=s.episode_id LEFT JOIN staff u ON u.id=s.therapist_id ';$count=(int)q('SELECT COUNT(*)'.$join.'WHERE '.$where,$a)->fetchColumn();$pages=max(1,(int)ceil($count/50));$page=max(1,min($page,$pages));$rows=q('SELECT s.id,s.starts_at,s.status,s.pain_before,s.pain_after,s.rom,s.notes,u.name therapist'.$join.'WHERE '.$where.' ORDER BY s.starts_at,s.id LIMIT 50 OFFSET '.(($page-1)*50),$a)->fetchAll();return compact('rows','count','page','pages');
}
function progressView():void{$pid=(int)($_GET['pid']??0);try{$d=progressData($pid,(int)($_GET['p']??1));}catch(DomainException $e){http_response_code(403);echo e($e->getMessage());return;}layout('patients','روند درمان پرونده '.fa($pid),'اندازه‌گیری‌ها و یادداشت‌های ثبت‌شده؛ مقدار خالی به معنی ثبت‌نشده است.');echo '<section class="panel"><div class="table-scroll"><table><thead><tr><th>جلسه</th><th>درمانگر</th><th>وضعیت</th><th>درد قبل</th><th>درد بعد</th><th>دامنه حرکت</th><th>نتیجه</th></tr></thead><tbody>';foreach($d['rows'] as $r)echo '<tr><td>'.jd($r['starts_at'],'yyyy/MM/dd HH:mm').'</td><td>'.e($r['therapist']).'</td><td>'.badge($r['status']).'</td><td>'.e($r['pain_before']??'—').'</td><td>'.e($r['pain_after']??'—').'</td><td>'.e($r['rom']).'</td><td>'.nl2br(e($r['notes'])).'</td></tr>';echo '</tbody></table></div><div class="actions">';foreach([$d['page']-1=>'قبل',$d['page']+1=>'بعد'] as $p=>$label)if($p>=1&&$p<=$d['pages'])echo '<a class="button secondary" href="/progress?pid='.$pid.'&amp;p='.$p.'">'.$label.'</a>';echo '</div></section>';endLayout();}
