<?php
$view=substr($path,9)?:'home';$pid=(int)($_SESSION['pid']??0);$patient=$pid?(q("SELECT * FROM patients WHERE pid=? AND active=1 AND allow_patient_portal='YES'",[$pid])->fetch()?:null):null;
if(!$patient&&$view!=='login')go('/patient/login');
$notice='';$error='';$ready=setting('otp')==='1';
if($_SERVER['REQUEST_METHOD']==='POST'){
 checkcsrf();try{$action=val('action',30,true);
 if($action==='logout'){$_SESSION=[];session_regenerate_id(true);go('/patient/login');}
 if($view==='login'){
  if(!$ready)throw new DomainException('ورود پیامکی هنوز توسط کلینیک فعال نشده است.');$sms=json_decode(file_get_contents($config['storage'].'/sms.json'),true,512,JSON_THROW_ON_ERROR);
  $send=function($mobile,$code)use($sms){$ch=curl_init('https://api.kavenegar.com/v1/'.rawurlencode($sms['key']).'/verify/lookup.json');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['receptor'=>$mobile,'token'=>$code,'template'=>$sms['template'],'type'=>'sms']),CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>8,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);$out=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);return $http===200&&(int)(json_decode((string)$out,true)['return']['status']??0)===200;};
  $otp=new MasihaOtp($db,$config['secret'],$send);
  if($action==='otp_send'){$_SESSION['otp_id']=$otp->request(val('mobile',20,true),$_SERVER['REMOTE_ADDR']??'');$notice='اگر این شماره برای پرونده شما فعال باشد، کد ورود پیامک می‌شود. کد ۳ دقیقه اعتبار دارد.';}
  elseif($action==='otp_verify'){$p=$otp->verify($_SESSION['otp_id']??'',val('code',6,true));if(!$p)throw new DomainException('کد درست نیست یا اعتبار آن تمام شده است.');session_regenerate_id(true);$_SESSION=['pid'=>(int)$p['pid'],'csrf'=>bin2hex(random_bytes(32)),'last_seen'=>time()];audit('patient_login',$p['pid']);go('/patient/home');}
 }elseif($patient){
  if($action==='book'){
   $id=num('slot_id',1);$eid=num('episode_id',1);schedulingLock();try{$db->beginTransaction();
    $slot=q('SELECT x.* FROM physio_slots x JOIN staff u ON u.id=x.therapist_id AND u.active=1 WHERE x.id=? AND x.enabled=1 AND x.starts_at>NOW() FOR UPDATE',[$id])->fetch();
    $ep=q("SELECT * FROM physio_episodes WHERE id=? AND pid=? AND status='active' FOR UPDATE",[$eid,$pid])->fetch();if(!$slot||!$ep)throw new DomainException('زمان یا دوره انتخاب‌شده دیگر قابل رزرو نیست.');
    if((int)q("SELECT COUNT(*) FROM physio_sessions WHERE episode_id=? AND status IN ('scheduled','done')",[$eid])->fetchColumn()>=(int)$ep['planned_sessions'])throw new DomainException('همه جلسات این دوره رزرو یا انجام شده‌اند.');
    if(conflict($slot['starts_at'],$slot['ends_at'],$slot['therapist_id'],$slot['room'],$slot['equipment'],$pid))throw new DomainException('این زمان دیگر آزاد نیست. زمان دیگری انتخاب کنید.');
    q("INSERT INTO physio_sessions(episode_id,therapist_id,starts_at,ends_at,room,equipment,treatment,notes,created_by) VALUES(?,?,?,?,?,?,'جلسه فیزیوتراپی','',?)",[$eid,$slot['therapist_id'],$slot['starts_at'],$slot['ends_at'],$slot['room'],$slot['equipment'],-$pid]);audit('patient_booked',(int)$db->lastInsertId());$db->commit();
   }catch(Throwable $ex){if($db->inTransaction())$db->rollBack();throw $ex;}finally{schedulingUnlock();}flash('نوبت شما ثبت شد.');go('/patient/booking');
  }
  if($action==='upload'){uploadDocument($pid);flash('مدرک شما ثبت شد.');go('/patient/documents');}
  elseif($action==='cancel'){$id=num('session_id',1);$s=q("SELECT s.id FROM physio_sessions s JOIN physio_episodes ep ON ep.id=s.episode_id WHERE s.id=? AND ep.pid=? AND s.status='scheduled' AND s.starts_at>NOW()",[$id,$pid])->fetchColumn();if(!$s)throw new DomainException('این نوبت قابل لغو نیست.');q("UPDATE physio_sessions SET status='cancelled' WHERE id=?",[$id]);audit('patient_cancelled',$id);flash('نوبت لغو شد.');go('/patient/booking');}
 }
 }catch(Throwable $ex){if($db->inTransaction())$db->rollBack();$error=$ex instanceof DomainException?$ex->getMessage():'درخواست انجام نشد. دوباره تلاش کنید یا با پذیرش تماس بگیرید.';}
}
head('پرونده من');?>
<main class="portal-shell"><header class="portal-header"><h1><?=e(setting('name','مدیریت کلینیک مسیحا'))?></h1><?php if($patient):?><form method="post"><?php csrf();?><input type="hidden" name="action" value="logout"><button class="button secondary">خروج</button></form><?php else:?><a href="/login" class="muted">ورود کارکنان</a><?php endif;?></header>
<?php if($error):?><div class="notice error" role="alert"><?=e($error)?></div><?php endif;if($notice):?><div class="notice success" role="status"><?=e($notice)?></div><?php endif;if(isset($_SESSION['flash'])):?><div class="notice success"><?=e($_SESSION['flash'])?></div><?php unset($_SESSION['flash']);endif;?>
<?php if($view==='login'):?><section class="panel portal-card"><span class="soft-icon"><?=icon('heart')?></span><h2>ورود به پرونده من</h2><p class="muted">بدون رمز ثابت و بدون ایمیل؛ با شماره همراه خود وارد شوید.</p><?php if(!$ready):?><div class="notice" style="margin-top:24px;background:#f4f8f4">ورود پیامکی هنوز فعال نشده است. لطفاً با پذیرش تماس بگیرید.</div><?php else:formstart('otp_send');field('mobile','شماره همراه','','tel','شماره همراهی که به پذیرش داده‌اید.',true,false,'autocomplete="tel"');?><button class="button primary full">دریافت کد ورود</button></form><?php if(isset($_SESSION['otp_id'])):formstart('otp_verify');field('code','کد پیامک‌شده','','text','کد ۶ رقمی پیامک؛ اعتبار آن ۳ دقیقه است.',true,false,'inputmode="numeric" autocomplete="one-time-code" maxlength="6"');?><button class="button primary full">ورود به پرونده</button></form><?php endif;endif;?><p class="hint">شماره تماس کلینیک: <?=fa(setting('phone','هنوز ثبت نشده'))?></p></section>
<?php else:?><h2><?=e(patientName($patient))?>، خوش آمدید</h2><p class="muted">نوبت‌ها، مدارک و مسیر درمان شما</p><nav class="portal-nav"><a href="/patient/booking">نوبت‌های من</a><a href="/patient/documents">مدارک من</a><a href="/patient/treatment">روند درمان من</a></nav>
<?php if(in_array($view,['home','booking'],true)):?><section class="panel"><h2>نوبت‌های من</h2><?php $rows=sessions('p.pid=?',[$pid]);if(!$rows)emptyState('نوبتی ثبت نشده','برای دریافت نوبت با پذیرش کلینیک تماس بگیرید.');foreach($rows as $s):?><div class="resource-row"><span class="soft-icon"><?=icon('calendar')?></span><div><strong><?=jd($s['starts_at'],'EEEE d MMMM yyyy، HH:mm')?></strong><p><?=e($s['therapist_name'])?> · <?=e($s['room'])?></p><?=badge($s['status'])?></div><?php if($s['status']==='scheduled'&&$s['starts_at']>date('Y-m-d H:i:s')):formstart('cancel');?><input type="hidden" name="session_id" value="<?=$s['id']?>"><button class="button secondary" type="submit">لغو نوبت</button></form><?php endif;?></div><?php endforeach;?><p class="hint">برای رزرو یا تغییر زمان با پذیرش تماس بگیرید: <?=fa(setting('phone','شماره ثبت نشده'))?></p></section><?php endif;?>
<?php if($view==='booking'):?><section class="panel"><h2>گرفتن نوبت جدید</h2><p class="muted">دوره درمان و سپس زمان مناسب را انتخاب کنید.</p><?php $eps=q("SELECT * FROM physio_episodes WHERE pid=? AND status='active'",[$pid])->fetchAll();$slots=q("SELECT x.*,u.name FROM physio_slots x JOIN staff u ON u.id=x.therapist_id AND u.active=1 WHERE x.enabled=1 AND x.starts_at>NOW() ORDER BY x.starts_at LIMIT 60")->fetchAll();$available=[];foreach($slots as $slot)if(!conflict($slot['starts_at'],$slot['ends_at'],$slot['therapist_id'],$slot['room'],$slot['equipment'],$pid))$available[]=$slot;
if(!$eps)emptyState('دوره درمان فعالی ندارید','پذیرش کلینیک باید ابتدا دوره درمان شما را ثبت کند.');elseif(!$available)emptyState('فعلاً زمان آزادی اعلام نشده','کمی بعد مراجعه کنید یا با پذیرش تماس بگیرید.');else{formstart('book');$opts=[''=>'انتخاب دوره'];foreach($eps as $ep)$opts[$ep['id']]=$ep['diagnosis'];selectfield('episode_id','برای کدام دوره؟',$opts,'','دوره‌ای که می‌خواهید برای آن جلسه رزرو کنید.',true);?><div class="booking-options"><?php foreach($available as $slot):?><label class="booking-option"><input type="radio" name="slot_id" value="<?=$slot['id']?>" required><span><strong><?=jd($slot['starts_at'],'EEEE d MMMM، HH:mm')?></strong><small><?=e($slot['name'])?> · <?=e($slot['room'])?></small></span></label><?php endforeach;?></div><button class="button primary full" type="submit">تأیید و ثبت نوبت</button></form><?php }?></section><?php endif;?>
<?php if($view==='documents'):?><section class="panel"><h2>مدارک من</h2><?php foreach(q('SELECT * FROM physio_patient_documents WHERE pid=? ORDER BY id DESC',[$pid])->fetchAll() as $d):?><a class="document-row" href="/document?id=<?=$d['id']?>"><?=icon('file')?><?=e($d['title'])?><span><?=jd($d['created_at'])?></span></a><?php endforeach;formstart('upload',true);field('title','این مدرک چیست؟','','text','مانند گزارش پزشک یا عکس زانو.',true);field('file','انتخاب مدرک از گوشی','','file','PDF یا عکس JPG و PNG تا ۱۰ مگابایت.',true,false,'accept="application/pdf,image/png,image/jpeg"');?><button class="button primary full">فرستادن مدرک</button></form></section><?php endif;?>
<?php if($view==='treatment'):foreach(q('SELECT * FROM physio_episodes WHERE pid=? ORDER BY id DESC',[$pid])->fetchAll() as $ep):$done=(int)q("SELECT COUNT(*) FROM physio_sessions WHERE episode_id=? AND status='done'",[$ep['id']])->fetchColumn();?><section class="panel"><h2><?=e($ep['diagnosis'])?></h2><p><?=fa($done)?> جلسه از <?=fa($ep['planned_sessions'])?> جلسه انجام شده</p><div class="progress"><span style="width:<?=min(100,$done/$ep['planned_sessions']*100)?>%"></span></div><h3 style="margin-top:24px">تمرین‌های خانگی شما</h3><p><?=nl2br(e($ep['exercises']?:'هنوز تمرینی ثبت نشده است.'))?></p><h3 style="margin-top:20px">هدف‌های درمان</h3><p><?=nl2br(e($ep['goals']))?></p></section><?php endforeach;endif;endif;?>
<footer class="footer"><?=e(setting('address'))?></footer></main></body></html>
