CREATE TABLE IF NOT EXISTS discount_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 kind VARCHAR(10) NOT NULL,
 value BIGINT UNSIGNED NOT NULL,
 active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS episode_billing (
 episode_id BIGINT UNSIGNED PRIMARY KEY,
 mode VARCHAR(20) NOT NULL,
 base_toman BIGINT UNSIGNED NOT NULL,
 discount_id BIGINT UNSIGNED NULL,
 discount_name VARCHAR(160) NOT NULL DEFAULT '',
 discount_kind VARCHAR(10) NOT NULL DEFAULT 'fixed',
 discount_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
 discount_toman BIGINT UNSIGNED NOT NULL DEFAULT 0,
 net_toman BIGINT UNSIGNED NOT NULL,
 package_id BIGINT UNSIGNED NULL,
 package_snapshot LONGTEXT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS billing_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 entity_type VARCHAR(30) NOT NULL,
 entity_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(40) NOT NULL,
 actor_id BIGINT NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 details LONGTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(entity_type,entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
