CREATE TABLE IF NOT EXISTS visit_history_links (
 source_hash CHAR(64) PRIMARY KEY,
 pid BIGINT NOT NULL,
 decision VARCHAR(20) NOT NULL,
 session_id BIGINT UNSIGNED NULL,
 evidence_hash CHAR(64) NOT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 reason VARCHAR(1000) NOT NULL,
 actor_id BIGINT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(session_id), INDEX(pid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS visit_history_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 source_hash CHAR(64) NOT NULL,
 pid BIGINT NOT NULL,
 version INT UNSIGNED NOT NULL,
 actor_id BIGINT NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 details LONGTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(source_hash,version), INDEX(pid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
