ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS session_id BIGINT UNSIGNED NULL;
ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS request_key CHAR(32) NULL;
ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS reversal_of BIGINT UNSIGNED NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_stock_request ON inventory_movements(request_key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stock_reversal ON inventory_movements(reversal_of);
CREATE INDEX IF NOT EXISTS idx_stock_session ON inventory_movements(session_id);
CREATE TABLE IF NOT EXISTS stock_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,item_id BIGINT UNSIGNED NOT NULL,actor_id BIGINT NOT NULL,action VARCHAR(40) NOT NULL,details LONGTEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(item_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS document_types(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,active TINYINT NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE physio_patient_documents ADD COLUMN IF NOT EXISTS document_type_id BIGINT UNSIGNED NULL;
CREATE TABLE IF NOT EXISTS sms_audience_previews(id CHAR(32) PRIMARY KEY,actor_id BIGINT NOT NULL,title VARCHAR(160) NOT NULL,message TEXT NOT NULL,filters TEXT NOT NULL,recipients LONGTEXT NOT NULL,expires_at DATETIME NOT NULL,campaign_id BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS document_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,document_id BIGINT UNSIGNED NOT NULL,actor_id BIGINT NOT NULL,old_type BIGINT UNSIGNED NULL,new_type BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(document_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
