CREATE TABLE IF NOT EXISTS physio_slots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, therapist_id BIGINT NOT NULL,
 starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL,
 room VARCHAR(100) NOT NULL, equipment VARCHAR(100) NOT NULL DEFAULT '',
 enabled TINYINT NOT NULL DEFAULT 1, created_by BIGINT NOT NULL,
 UNIQUE KEY unique_slot(therapist_id,starts_at), INDEX(starts_at),CHECK(ends_at>starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS physio_patient_documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, pid BIGINT NOT NULL,
 title VARCHAR(150) NOT NULL, storage_name VARCHAR(80) NOT NULL UNIQUE,
 mime VARCHAR(60) NOT NULL, bytes INT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(pid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
