CREATE TABLE IF NOT EXISTS physio_episodes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 pid BIGINT NOT NULL, diagnosis VARCHAR(255) NOT NULL, body_region VARCHAR(100) NOT NULL,
 referral VARCHAR(255) NOT NULL DEFAULT '', assessment TEXT NOT NULL, goals TEXT NOT NULL,
 precautions TEXT NOT NULL, exercises TEXT NOT NULL,
 planned_sessions SMALLINT UNSIGNED NOT NULL, fee_toman BIGINT UNSIGNED NOT NULL DEFAULT 0,
 status ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
 created_by BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(pid), CHECK(planned_sessions BETWEEN 1 AND 365)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS physio_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, episode_id BIGINT UNSIGNED NOT NULL,
 therapist_id BIGINT NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL,
 room VARCHAR(100) NOT NULL, equipment VARCHAR(100) NOT NULL DEFAULT '',
 status ENUM('scheduled','done','cancelled','absent') NOT NULL DEFAULT 'scheduled',
 pain_before TINYINT UNSIGNED NULL, pain_after TINYINT UNSIGNED NULL,
 rom VARCHAR(255) NOT NULL DEFAULT '', treatment TEXT NOT NULL, notes TEXT NOT NULL,
 created_by BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (episode_id) REFERENCES physio_episodes(id), INDEX(starts_at,ends_at),
 CHECK(ends_at>starts_at), CHECK(pain_before BETWEEN 0 AND 10), CHECK(pain_after BETWEEN 0 AND 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS physio_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, episode_id BIGINT UNSIGNED NOT NULL,
 amount_toman BIGINT NOT NULL, reference VARCHAR(100) NOT NULL DEFAULT '',
 created_by BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (episode_id) REFERENCES physio_episodes(id), CHECK(amount_toman<>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS physio_audit (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_id BIGINT NOT NULL,
 action VARCHAR(60) NOT NULL, entity_id BIGINT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
