<?php
// Local stdin/stdout IPC only. Never place under public/ or invoke config in logs.
if(PHP_SAPI!=='cli')exit(1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/import.php';
function response($v):never{echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
try{$in=json_decode(stream_get_contents(STDIN),true,32,JSON_THROW_ON_ERROR);$op=$in['op']??'';
 if($op==='config'){$r=q("SELECT * FROM import_runs WHERE status='running' ORDER BY id LIMIT 1")->fetch();if(!$r)response(['active'=>false]);$c=importConfig();if($r['account_key']!==importAccount($c)||!$c['password_cipher']){q("UPDATE import_runs SET status='blocked',message='تنظیمات حساب تغییر کرده یا رمز ذخیره نشده است.' WHERE id=?",[$r['id']]);response(['active'=>false]);}$c['password']=importDecrypt($c['password_cipher']);unset($c['password_cipher']);response(['active'=>true,'run'=>$r,'connection'=>$c,'storage'=>$config['storage']]);}
 $id=(int)($in['run_id']??0);$r=q('SELECT * FROM import_runs WHERE id=?',[$id])->fetch();if(!$r)response(['error'=>'missing']);
 if($op==='cursor'){$p=max(1,(int)($in['page']??1));$row=max(0,(int)($in['row']??0));q("UPDATE import_runs SET page_no=?,row_no=? WHERE id=? AND status='running'",[$p,$row,$id]);response(['ok'=>true]);}
 if($op==='state'){response(['run'=>$r,'free'=>disk_free_space($config['storage'])]);}
 if($op==='stop'){$status=in_array($in['status']??'',['blocked','error','complete','space'])?$in['status']:'error';$messages=['blocked'=>'ورود، تأیید انسانی یا سطح دسترسی نیاز به بررسی دارد.','error'=>'ساختار صفحه یا اتصال معتبر نبود؛ برای جلوگیری از جاافتادن پرونده انتقال متوقف شد.','complete'=>'به پایان صفحه‌بندی فهرست رسیدیم. رکوردهای آرشیو را بررسی کنید.','space'=>'سقف آرشیو یا حداقل فضای آزاد دیسک رعایت نشده؛ انتقال متوقف شد.'];q("UPDATE import_runs SET status=?,message=? WHERE id=? AND status='running'",[$status,$messages[$status],$id]);q('INSERT INTO import_events(run_id,code,page_no,row_no) VALUES(?,?,?,?)',[$id,preg_replace('/[^a-z_]/','',substr((string)($in['code']??$status),0,40)),$r['page_no'],$r['row_no']]);response(['ok'=>true]);}
 if($op==='reserve'){$db->beginTransaction();$r=q('SELECT * FROM import_runs WHERE id=? FOR UPDATE',[$id])->fetch();if($r['status']!=='running'){$db->commit();response(['ok'=>false,'stop'=>true]);}if($r['processed']>=$r['total_limit']){q("UPDATE import_runs SET status='limit',message='سقف کل بررسی پرونده‌ها تکمیل شد.' WHERE id=?",[$id]);$db->commit();response(['ok'=>false,'stop'=>true]);}q('INSERT IGNORE INTO import_quota(account_key,window_start,attempts,next_at) VALUES(?,NOW(),0,NOW())',[$r['account_key']]);$quota=q('SELECT *,TIMESTAMPDIFF(SECOND,NOW(),next_at) wait_seconds,TIMESTAMPDIFF(SECOND,window_start,NOW()) elapsed FROM import_quota WHERE account_key=? FOR UPDATE',[$r['account_key']])->fetch();$attempts=(int)$quota['attempts'];if((int)$quota['elapsed']>=3600){$attempts=0;q('UPDATE import_quota SET attempts=0,window_start=NOW() WHERE account_key=?',[$r['account_key']]);}$wait=max(0,(int)$quota['wait_seconds']);if($attempts>=(int)$r['hourly_limit'])$wait=max($wait,3600-(int)$quota['elapsed']);if($wait>0){q('UPDATE import_runs SET not_before=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE id=?',[$wait,$id]);$db->commit();response(['ok'=>false,'wait'=>$wait]);}$used=(int)q('SELECT (SELECT COALESCE(SUM(bytes),0) FROM import_records)+(SELECT COALESCE(SUM(bytes),0) FROM import_versions)')->fetchColumn();if($used>=(int)$r['storage_mb']*1048576||disk_free_space($config['storage'])<536870912){q("UPDATE import_runs SET status='space',message='فضای کافی برای ادامه نیست.' WHERE id=?",[$id]);$db->commit();response(['ok'=>false,'stop'=>true]);}$delay=(int)ceil(3600/(int)$r['hourly_limit']);q('UPDATE import_quota SET attempts=attempts+1,next_at=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE account_key=?',[$delay,$r['account_key']]);q('UPDATE import_runs SET not_before=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE id=?',[$delay,$id]);$db->commit();response(['ok'=>true]);}
 if($op==='save'){$record=$in['record']??[];$payload=json_encode($record,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$bytes=strlen($payload);if($bytes>1048576)throw new RuntimeException('record_size');$key=$record['source_key']??'';if(!preg_match('/^[0-9a-f]{64}$/D',$key))throw new RuntimeException('key');$db->beginTransaction();$r=q('SELECT * FROM import_runs WHERE id=? FOR UPDATE',[$id])->fetch();if(!in_array($r['status'],['running','paused'])){$db->commit();response(['ok'=>false,'stop'=>true]);}$existing=q('SELECT id,bytes,payload,payload_hash FROM import_records WHERE account_key=? AND source_key=? FOR UPDATE',[$r['account_key'],$key])->fetch();$used=(int)q('SELECT (SELECT COALESCE(SUM(bytes),0) FROM import_records)+(SELECT COALESCE(SUM(bytes),0) FROM import_versions)')->fetchColumn();if($used+$bytes>(int)$r['storage_mb']*1048576){q("UPDATE import_runs SET status='space',message='سقف حجم آرشیو تکمیل شد؛ رکورد جاری ذخیره نشد.' WHERE id=?",[$id]);$db->commit();response(['ok'=>false,'stop'=>true]);}$vals=[$record['page'],$record['row'],mb_substr($record['name']??'',0,255),substr($record['national_id']??'',0,20),substr($record['mobile']??'',0,30),in_array($record['confidence']??'',['national','contact'])?$record['confidence']:'review',$payload,hash('sha256',$payload),$bytes,($record['complete']??false)?'tabs_saved':'partial'];if($existing&&$existing['payload_hash']!==hash('sha256',$payload))q('INSERT INTO import_versions(record_id,payload,bytes) VALUES(?,?,?)',[$existing['id'],$existing['payload'],$existing['bytes']]);if($existing)q('UPDATE import_records SET source_page=?,source_row=?,display_name=?,national_id=?,mobile=?,confidence=?,payload=?,payload_hash=?,bytes=?,completeness=? WHERE id=?',[...$vals,$existing['id']]);else q('INSERT INTO import_records(source_page,source_row,display_name,national_id,mobile,confidence,payload,payload_hash,bytes,completeness,account_key,source_key,run_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[...$vals,$r['account_key'],$key,$id]);$recordId=$existing?(int)$existing['id']:(int)$db->lastInsertId();$registration=null;if(importPatientAutoEnabled())$registration=importRegisterRecord($recordId,(int)$r['created_by']);$nextPage=max(1,(int)$in['next_page']);$nextRow=max(0,(int)$in['next_row']);q('UPDATE import_runs SET processed=processed+1,saved=saved+?,duplicates=duplicates+?,page_no=?,row_no=?,message=? WHERE id=?',[$existing?0:1,$existing?1:0,$nextPage,$nextRow,'رکورد ذخیره شد؛ در انتظار سهمیه بعدی.',$id]);$db->commit();response(['ok'=>true,'duplicate'=>(bool)$existing,'registration'=>$registration]);}
 response(['error'=>'operation']);
}catch(Throwable $ex){if(isset($db)&&$db->inTransaction())$db->rollBack();fwrite(STDERR,'import bridge failed: '.get_class($ex)."\n");exit(1);}
